      REAL FUNCTION CROSS(X1,Y1,X2,Y2)
C
C     DETERMINES THE POINT WHERE TWO LINES CROSS
C
C     MODULE ADAPTED FROM WEPP VERSION 2004.7 AND CALLED FROM 
C     SUBROUTINE EROD
C
C     AUTHOR(S): D.C. FLANAGAN AND J.C. ASCOUGH II
C     DATE LAST MODIFIED: 9-30-2004
C
C     + + + ARGUMENT DECLARATIONS + + +
C
      REAL X1, Y1, X2, Y2
C
C     + + + ARGUMENT DEFINITIONS + + +
C
C     X1 -  POINT 1 X VALUE
C     Y1 -  POINT 1 Y VALUE
C     X2 -  POINT 2 X VALUE
C     Y2 -  POINT 2 Y VALUE
C
C     + + + LOCAL VARIABLES + + +
C
      REAL SLOPE
C
C     + + + LOCAL VARIABLE DEFINITIONS + + +
C
C     SLOPE - SLOPE OF LINE SEGMENT
C
C     BEGIN FUNCTION CROSS
C
      IF (X1.NE.X2) THEN
         SLOPE = (Y2-Y1) / (X2-X1)
      ELSE
         SLOPE = 1.0E6
      END IF
C     
      CROSS = -Y1 / SLOPE + X1
C     
      RETURN
      END
