      REAL FUNCTION DEPC(XU,A,B,PHI,THETA,DU,KTRATO,QOSTAR)
C
C     FUNCTION DEPC COMPUTES A PORTION OF THE DEPOSITION EQUATION
C
C     MODULE ADAPTED FROM WEPP VERSION 2004.7 AND CALLED FROM
C     SUBROUTINE ROUTE IN TWO LOCATIONS
C
C     AUTHOR(S): D.C FLANAGAN AND J.C. ASCOUGH II
C     DATE LAST MODIFIED: 9-30-2004
C
C     + + + ARGUMENT DECLARATIONS + + +
C
      REAL XU, A, B, PHI, THETA, DU, KTRATO, QOSTAR
C
C     + + + ARGUMENT DEFINITIONS + + +
C
C     XU     - NONDIMENSIONAL DISTANCE ON AN PLANE WHERE CURRENT
C              DEPOSITION REGION BEGINS
C     A      - "A" SHEAR STRESS COEFFICIENT FOR CURRENT SLOPE
C               SECTION
C     B      - "B" SHEAR STRESS COEFFICIENT FOR CURRENT SLOPE
C              SECTION
C     PHI    - NONDIMENSIONAL DEPOSITION PARAMETER FOR CURRENT PLANE
C     THETA  - NONDIMENSIONAL INTERRILL DETACHMENT PARAMETER FOR
C              CURRENT PLANE
C     DU     - DEPOSITION RATE AT XU
C     KTRATO - NONDIMENSIONAL TRANSPORT CAPACITY COEFFICIENT
C     QOSTAR - NONDIMENSIONAL FLOW DISCHARGE ONTO AN PLANE
C
C     + + + LOCAL VARIABLES + + +
C     + + + LOCAL VARIABLE DEFINITIONS + + +
C
C     BEGIN FUNCTION DEPC
C
      IF (ABS(QOSTAR+XU).GE.10E-8) THEN
         DEPC = DU - (A*KTRATO*PHI*2.0*(QOSTAR+XU)/(PHI+2.0)) - ((B*
     1       KTRATO-2.0*A*KTRATO*QOSTAR-THETA)*PHI/(PHI+1.0))
      ELSE
         DEPC = 0.0
      END IF
C     
      RETURN
      END
