      SUBROUTINE DEPEQS(XU,CDEP,A,B,PHI,THETA,X,DEPEQ,KTRATO,QOSTAR)
C
C     SOLVES THE DEPOSITION EQUATION.
C
C     MODULE ADAPTED FROM WEPP VERSION 2004.7 AND CALLED FROM 
C     SUBROUTINE DEPOS
C
C     AUTHOR(S): D.C FLANAGAN AND J.C. ASCOUGH II
C     DATE LAST MODIFIED: 9-30-2004
C
C     + + + ARGUMENT DECLARATIONS + + +
C
      REAL XU, CDEP, A, B, PHI, THETA, X, DEPEQ, KTRATO, QOSTAR
C
C     + + + ARGUMENT DEFINITIONS + + +
C
C     XU     - NONDIMENSIONAL DISTANCE ON AN OFE WHERE CURRENT
C              DEPOSITION REGION BEGINS
C     CDEP   -
C     A      - SHEAR STRESS COEFFICIENT FOR CURRENT SLOPE SECTION
C     B      - SHEAR STRESS COEFFICIENT FOR CURRENT SLOPE SECTION
C     PHI    - NONDIMENSIONAL DEPOSITION PARAMETER FOR CURRENT OFE
C     THETA  - NONDIMENSIONAL INTERRILL DETACHMENT PARAMETER FOR
C              CURRENT OFE
C     X      -
C     DEPEQ  -
C     KTRATO - NONDIMENSIONAL SEDIMENT TRANSPORT EQN. COEFFICIENT
C     QOSTAR - NONDIMENSIONAL FLOW DISCHARGE ONTO TOP OF OFE.
C
C     + + + LOCAL VARIABLES + + +
C
      REAL RATIO, EXPON, TMPVR1
C
C     + + + LOCAL VARIABLE DEFINITIONS + + +
C
C     RATIO  - TEMP VARIABLE TO STORE PARTS OF THE DEPEQ EQUATION
C     EXPON  - TEMP VARIABLE TO STORE PARTS OF THE DEPEQ EQUATION
C
C     + + + SUBROUTINES CALLED + + +
C
C     UNDFLO
C
C     BEGIN SUBROUTINE DEPEQS
C
      IF (ABS(QOSTAR+X).LT.10E-8) X = -QOSTAR - 0.000001
      RATIO = (XU+QOSTAR) / (X+QOSTAR)
      IF (QOSTAR.GE.0.0.AND.RATIO.GT.1.0) RATIO = 1.0
C     
      EXPON = 1.0 + PHI
      CALL UNDFLO(RATIO,EXPON)
C     
      TMPVR1 = 2.0 * A * KTRATO
C     
      DEPEQ = (TMPVR1*PHI*(X+QOSTAR)/(2.0+PHI)) + (PHI/(1.0+PHI)) * (B*
     1    KTRATO-THETA-(TMPVR1*QOSTAR)) + CDEP * RATIO ** EXPON
C     
      RETURN
      END
