      REAL FUNCTION DEPEND(XU,XL,A,B,CDEP,PHI,THETA,KTRATO,QOSTAR)
C
C     FUNCTION DEPEND (FOR A SEGMENT OF A FLOW PLANE THAT HAS 
C     DEPOSITION AT THE BEGINNING) USES THE ANALYTIC SOLUTION TO THE 
C     DEPOSITION EQUATION TO CALCULATE WHERE DEPOSITION ENDS
C
C     MODULE ADAPTED FROM WEPP VERSION 2004.7 AND CALLED FROM 
C     SUBROUTINE ROUTE
C
C     AUTHOR(S): D.C FLANAGAN AND J.C. ASCOUGH II
C     DATE LAST MODIFIED: 9-30-2004
C
C     + + + ARGUMENT DECLARATIONS + + +
C
      REAL XU, XL, A, B, CDEP, PHI, THETA, KTRATO, QOSTAR
C
C     + + + ARGUMENT DEFINITIONS + + +
C
C     XU     - N.D. DISTANCE AT TOP OF SLOPE SEGMENT
C     XL     - N.D. DISTANCE AT END OF SLOPE SEGMENT
C     A      - SHEAR STRESS EQUATION COEFFICIENT
C     B      - SHEAR STRESS EQUATION COEFFICIENT
C     CDEP   - PORTION OF THE SOLUTION TO DEPOSITION EQUATION
C     PHI    - N.D. DEPOSITION PARAMETER
C     THETA  - N.D. INTERRILL DETACHMENT PARAMETER
C     KTRATO - DIMENSIONLESS TRANSPORT COEFFICIENT
C     QOSTAR - DIMENSIONLESS FLOW DISCHARGE ONTO TOP OF OFE
C
C     + + + LOCAL VARIABLES + + +
C
      REAL XDEND, R1, R2, RATIO, EXPON, F, DF, XMIN, TMPVR1
      INTEGER J, KKKK, ITMPV1, LOOPFG
C
C     + + + LOCAL VARIABLE DEFINITIONS + + +
C
C     XDEND  - CURRENT TRIAL VALUE FOR N.D. DISTANCE WHERE
C              DEPOSITION ENDS
C     R1     - PORTION OF SOLUTION TO DEPOSITION EQUATION SOLVED
C              FOR CONDITIONS OF RATE EQUAL TO 0 AND BEGINNING
C              POINT EQUAL TO X=XU
C     R2     -   "       "          "          "        "
C     RATIO  -   "       "          "          "        "
C     EXPON  -   "       "          "          "        "
C     F      - CURRENT SOLUTION FOR DEPOSITION RATE AT X=XDEND
C     DF     - CURRENT SOLUTION FOR DERIVATIVE OF DEPOSITION RATE
C     J      - COUNTER VARIABLE - IN LOOP TO ONLY ALLOW A FINITE
C              NUMBER OF ITERATIONS TO DETERMINE WHERE DEP. ENDS
C     LOOPFG - FLAG. 1 = EXIT L1 LOOP
C
C     + + + SUBROUTINES CALLED + + +
C
C     UNDFLO
C
C     BEGIN SUBROUTINE DEPEND
C
C     SOLVE FOR FIRST TERM OF DEPOSITION EQUATION
C
      TMPVR1 = 2.0 * A * KTRATO
C     
      R1 = (PHI/(1.0+PHI)) * (B*KTRATO-THETA-(TMPVR1*QOSTAR))
C     
C     SOLVE FOR SECOND TERM OF DEPOSITION EQUATION
C     
      R2 = TMPVR1 * PHI / (2.0+PHI)
C     
C     IF FLOW IS INCREASING DOWN THE OFE, CHECK WHETHER DEPOSITION
C     AT THE END OF THE CURRENT SEGMENT (UNIFORM OR CONVEX SHAPE)
C     
      IF (QOSTAR.GE.0.0) THEN
         XDEND = XL
         RATIO = (XU+QOSTAR) / (XDEND+QOSTAR)
         EXPON = 1.0 + PHI
C        
         CALL UNDFLO(RATIO,EXPON)
C        
C        DETERMINE DEPOSITION RATE AT X = XL (END OF SEGMENT) 
C        RETURN IF A NEGATIVE VALUE DEPOSITION OCCURS FROM XU TO XL
C        
         F = R1 + R2 * (XDEND+QOSTAR) + CDEP * RATIO ** EXPON
         IF (F.LT.0.0) THEN
            DEPEND = XDEND
            RETURN
         END IF
C        
C        IF DEPOSITION NOT OCCURRING AT X=XL, SET BEGINNING POINT FOR
C        ITERATIVE SOLUTION FOR XDEND CLOSE TO X=XU
C        
         XDEND = XU + 0.01
         IF (XDEND.GT.XL) XDEND = (XU+XL) / 2.0
C     
C     FLOW IS DECREASING DOWN THE SEGMENT - FIRST CHECK 
C     TO DETERMINE THAT DEPOSITION DOES NOT IMMEDIATELY END
C     PAST THE INITIAL POINT (X=XU) AND THEN SET THE
C     BEGINNING POINT FOR THE ITERATIVE SOLUTION FOR XDEND
C     CLOSE TO X = XU
C     
      ELSE
C        
         IF (ABS(XU+QOSTAR).LE.0.0001) THEN
            DEPEND = -QOSTAR
            RETURN
         END IF
C        
         XDEND = XU + 0.0001
         IF (XDEND.GT.XL) XDEND = (XU+XL) / 2.0
         RATIO = (XU+QOSTAR) / (XDEND+QOSTAR)
         EXPON = 1.0 + PHI
         CALL UNDFLO(RATIO,EXPON)
C        
C        DETERMINE DEPOSITION AT X = XDEND, AND RETURN IF THE VALUE
C        IS POSITIVE OR ZERO
C        
         F = R1 + R2 * (XDEND+QOSTAR) + CDEP * RATIO ** EXPON
         IF (F.GE.0.0) THEN
            DEPEND = XDEND
            RETURN
         END IF
C     
      END IF    ! IF (QOSTAR.GE.0.0) THEN
C     
      LOOPFG = 0
      J = 0
      XMIN = XL
      KKKK = 0
C     
   10 CONTINUE
C     
      J = J + 1
C     
C     ITERATIVE SOLUTION FOR XDEND
C     
C     
C     SOLVE FOR PORTIONS OF THE DEPOSITION EQUATION
C     AT THE TRIAL VALUE OF XDEND
C     
      TMPVR1 = XDEND + QOSTAR
C     
      IF (ABS(TMPVR1).GT.0.0) THEN
         ITMPV1 = 1
      ELSE
         ITMPV1 = 0
      END IF
C     
      IF (ITMPV1.NE.0) THEN
         RATIO = (XU+QOSTAR) / TMPVR1
      ELSE
         RATIO = 1.0
      END IF
C     
      IF (RATIO.LT.0.0) RATIO = 1.0
      EXPON = 1.0 + PHI
C     
      CALL UNDFLO(RATIO,EXPON)
C     
C     SOLVE THE DEPOSITION EQUATION AT TRIAL VALUE OF XDEND
C     
      F = R1 + R2 * (XDEND+QOSTAR) + CDEP * RATIO ** EXPON
C     
C     CHECK ADDED TO FLAG IF ANY POSITIVE VALUES OF F HAVE BEEN 
C     CALCULATED BETWEEN XU AND XL, AND THEN TO RECORD THE POINT ON 
C     SLOPE WHERE THIS WAS FOUND
C     
      IF (F.GT.0.0.AND.QOSTAR.LT.0.0) THEN
         KKKK = KKKK + 1
         IF (XDEND.LT.XMIN) XMIN = XDEND
      END IF
C     
C     IF THE NONDIMENSIONAL DEPOSITION RATE IS LESS THAN 0.0001 THEN
C     JUMP OUT OF DO LOOP AND USE THE CURRENT VALUE OF XDEND AS THE 
C     POINT WHERE DEPOSITION IS PREDICTED TO END
C     
      IF (ABS(F).GT.0.0001) THEN
C        
         IF (ITMPV1.NE.0) THEN
C           
C           SOLVE FOR THE DERIVATIVE OF THE DEPOSITION FUNCTION
C           
            DF = R2 - (1.0+PHI) * CDEP * (RATIO**EXPON) / TMPVR1
            IF (ABS(DF).GT.0.0) THEN
C              
C              USE THE DERIVATIVE TO OBTAIN A NEW TRIAL VALUE FOR XDEND
C              
               XDEND = XDEND - F / DF
C              
               IF (QOSTAR.LT.0.0) THEN
                  IF (XDEND.LT.XU) XDEND = XU + 0.0001
                  IF (XDEND.GT.-QOSTAR) XDEND = -QOSTAR - 0.0001
                  IF (XDEND.GT.XL) XDEND = XL
               END IF
            ELSE
C              
C              IF THE DERIVATIVE IS ZERO AT THE POINT,
C              RESTART THE ITERATIONS WITH XDEND CLOSE TO XU
C              
               XDEND = XU + 0.0001
            END IF
         END IF
C        
         IF (XDEND.LT.XU) XDEND = XU + 0.0001
      ELSE
         LOOPFG = 1
      END IF
C     
      IF (J.LT.10.AND.LOOPFG.EQ.0) GO TO 10
C     
C     CHECK IF SOLUTION HAS NOT CONVERGED FOR A PLANE ON WHICH
C     FLOW IS DECREASING - IF IT HAS NOT AND NONE OF THE TRIAL
C     VALUES OF XDEND BETWEEN XU AND XL (OR -QOSTAR) HAVE PRODUCED
C     NON-NEGATIVE RESULTS THEN SET XDEND EQUAL TO XL
C     
      IF (LOOPFG.EQ.0.AND.QOSTAR.LT.0.0) THEN
         IF (KKKK.EQ.0) THEN
            XDEND = XL
         ELSE
            XDEND = XMIN
         END IF
      END IF
C     
      DEPEND = XDEND
C     
      RETURN
      END
