      SUBROUTINE ENRICH(KK,XTOP,XBOT,XDETST,LDTOP,LDBOT,LDDEND,THETA,
     1    IENDFG,SLPLEN,KTRATO,QIN,QOUT,QOSTAR,AINFTC,BINFTC,CINFTC,
     1    NPART,FRAC,FALL,FRCLY,FRSLT,FRSND,FRORG,SAND,SILT,CLAY,ORGMAT,
     1    FIDEL,TCF1,FRCFLW,ENRATO)
C
C     SUBROUTINE ENRICH COMPUTES THE NEW PARTICLE SIZE DISTRIBUTION 
C     OF SEDIMENT IN RUNOFF FOLLOWING ROUTING THROUGH A DEPOSITION 
C     REGION - THE EQUATION IS AN ANALYTICAL SOLUTION OF THE 
C     NONDIMENSIONAL SEDIMENT LOAD EQUATION FOR A DEPOSITIONAL REGION
C
C     MODULE ADAPTED FROM WEPP VERSION 2004.7 AND CALLED FROM 
C     SUBROUTINE ROUTE
C
C     AUTHOR(S): D.C. FLANAGAN AND J.C. ASCOUGH II
C     DATE LAST MODIFIED: 4-1-2005
C
C     + + + PARAMETER DECLARATIONS + + +
C
      INTEGER MXPART, MXNSL, MXSLP
      PARAMETER (MXPART = 10,MXNSL = 10,MXSLP = 40)
C
C     + + + ARGUMENT DECLARATIONS + + +
C
      INTEGER KK, IENDFG, PHIFLG, NPART
      REAL XTOP, XBOT, XDETST, THETA, LDTOP, LDBOT, LDDEND,
     1     SLPLEN, KTRATO, QIN, QOUT, QOSTAR, AINFTC(MXSLP), 
     1     BINFTC(MXSLP), CINFTC(MXSLP), FRAC(MXPART), FALL(MXPART),
     1     FRCLY(MXPART), FRSLT(MXPART), FRSND(MXPART), FRORG(MXPART),
     1     FIDEL(MXPART), TCF1(MXPART), FRCFLW(MXPART), ENRATO,
     1     SAND(MXNSL), SILT(MXNSL), CLAY(MXNSL), ORGMAT(MXNSL)
C
C     + + + ARGUMENT DEFINITIONS + + +
C
C     KK     - SLOPE SEGMENT NUMBER
C     XTOP   - NONDIMENSIONAL HORIZONTAL DISTANCE WHERE
C              DEPOSITION BEGINS
C     XBOT   - NONDIMENSIONAL HORIZONTAL DISTANCE WHERE
C              DEPOSITION ENDS
C     XDETST - NORMALIZED DISTANCE AT TOP OF DETACHMENT REGION
C     LDTOP  - NONDIMENSIONAL SEDIMENT LOAD AT XTOP
C     LDBOT  - NONDIMENSIONAL SEDIMENT LOAD AT XBOT
C     LDDEND - NOMALIZED SEDIMENT LOAD AT TOP OF DETACHMENT
C              REGION
C     THETA  - NONDIMENSIONAL INTERRILL DETACHMENT PARAMETER
C     IENDFG - FLAG TO INDICATE LAST CALL TO ENRICH AT THE END
C              OF A FLOW PLANE
C     PHIFLG - FLAG WHICH DETERMINES VALUE OF PHI
C     SLPLEN - LENGTH OF EACH OFE (M)
C     KTRATO - DIMENSIONLESS SED. TRANPORT EQN. COEFFICIENT
C     QIN    - FLOW DISCHARGE PER UNIT WIDTH (M^3/M*S) AT TOP OF OFE
C     QOUT   - FLOW DISCHARGE PER UNIT WIDTH (M^3/M*S) AT END OF OFE
C     QOSTAR - NONDIMENSIONAL DISCHARGE OF WATER ONTO AN OFE
C     AINFTC - N.D. SEDIMENT TRANSPORT COEFFICIENT
C     BINFTC - N.D. SEDIMENT TRANSPORT COEFFICIENT
C     CINFTC - N.D. SEDIMENT TRANSPORT COEFFICIENT
C     NPART  - NUMBER OF SEDIMENT PARTICLE CLASSES
C     FRAC   - FRACTION OF SEDIMENT IN EACH SIZE CLASS AT THE POINT
C     FALL   - SEDIMENT FALL VELOCITY FOR EACH SIZE CLASS (M/S)
C     FRCLY  - FRACTION OF CLAY IN EACH SIZE CLASS
C     FRSLT  - FRACTION OF SILT IN EACH SIZE CLASS
C     FRSND  - FRACTION OF SAND IN EACH SIZE CLASS
C     FRORG  - FRACTION OF ORGANIC MATTER IN EACH SIZE CLASS
C     FIDEL  - FRACTION OF EACH PARTICLE CLASS AFTER INTERRILL SORTING
C     TCF1   - FRACTION OF TOTAL SED. TRANSPORT CAPACITY FOR A CLASS
C     FRCFLW - FRACTION OF SEDIMENT IN EACH SIZE CLASS IN FLOW,
C              USUALLY REPORTED AS OUTPUT FOR THE END OF THE HILLSLOPE
C     ENRATO - SEDIMENT ENRICHMENT RATIO CALCULATED FOR THE HILLSLOPE
C
C
C     + + + LOCAL VARIABLES + + +
C
      REAL BETA, RATIO, EXPON, RATIO2, COEF1, COEF2, TERM1, TERM2, 
     1    TERM3, TERM4A, TERM4B, RATBOT, GADD, AA, BB, CC, PKRO, 
     1    GU(MXPART), GEND(MXPART), PHI, SSASOL, SUMG, SSASND, SSASLT, 
     1    SSACLY, SSAORG, SEDMAX(MXPART), SSASED, SUMSSA, 
     1    FTHETA(MXPART), INTLOD, RILLOD, TMPVR1, TMPVR2, TMPVR3, 
     1    TMPVR4, TMPVR5
      INTEGER I, IIFLAG
C
C     + + + LOCAL VARIABLE DEFINITIONS + + +
C
C     BETA   - RAINDROP INDUCED TURBULENCE COEFFICIENT
C              (EQUATION 11.2.4)
C     SUMSSA - VARIABLE USED TO SUM SSA FOR SEDIMENT
C              (EQUATION 11.5.5)
C     SUMG   - VARIABLE USED TO SUM SEDIMENT LOADS PREDICTED
C              BY EQUATION 11.5.1
C     SSASND - SPECIFIC SURFACE AREA OF SAND IN M**2/G
C     SSASLT - SPECIFIC SURFACE AREA OF SILT IN M**2/G
C     SSACLY - SPECIFIC SURFACE AREA OF CLAY IN M**2/G
C     SSAORG - SPECIFIC SURFACE AREA OF ORGANIC CARBON IN
C              M**2/G
C     AA     - ADJUSTED A TRANSPORT COEFFICIENT FOR PARTICLE
C              CLASS I
C     BB     - ADJUSTED B TRANSPORT COEFFICIENT FOR PARTICLE
C              CLASS I
C     CC     - ADJUSTED C TRANSPORT COEFFICIENT FOR PARTICLE
C              CLASS I
C     FTHETA - FRACTION OF INTERRILL DETACHMENT ATTRIBUTED TO
C              PARTICLE CLASS I
C     GU     - NONDIMENSIONAL SEDIMENT LOAD FOR PARTICLE
C              CLASS I AT X=XTOP
C     INTLOD - INTERRILL LOAD CONTRIBUTION FROM DETACHMENT REGION
C              ABOVE DEPOSITION REGION
C     RATIO  - RATIO OF X TERMS IN THE LAST COMPONENT OF
C              EQUATION 11.5.1
C     PHI    - NONDIMENSIONAL DEPOSITION PARAMETER FOR A
C              PARTICLE CLASS I (EQUATION 11.3.11)
C     EXPON  - PHI CORRECTION VARIABLE TO PREVENT MACHINE
C              OVERFLOW
C     RATIO2 - RATIO CORRECTION VARIABLE TO PREVENT MACHINE
C              OVERFLOW
C     COEF1  - COEFFICIENTS AND TERMS OF EQUATIONS 11.5.1 AND
C              11.5.2
C     COEF2  - COEFFICIENTS AND TERMS OF EQUATIONS 11.5.1 AND
C              11.5.2
C     TERM1  - COEFFICIENTS AND TERMS OF EQUATIONS 11.5.1 AND
C              11.5.2
C     TERM2  - COEFFICIENTS AND TERMS OF EQUATIONS 11.5.1 AND
C              11.5.2
C     TERM3  - COEFFICIENTS AND TERMS OF EQUATIONS 11.5.1 AND
C              11.5.2
C     TERM4A - COEFFICIENTS AND TERMS OF EQUATIONS 11.5.1 AND
C              11.5.2
C     TERM4B - COEFFICIENTS AND TERMS OF EQUATIONS 11.5.1 AND
C              11.5.2
C     GEND(MXPART)   : PREDICTED NONDIMENSIONAL SEDIMENT LOAD FOR THE
C                      PARTICLE CLASS I AT X=XBOT
C     SEDMAX(MXPART) : MAXIMUM POSSIBLE SEDIMENT LOAD IN A PARTICLE
C                      CLASS I AT X=XBOT
C     RATBOT - RUNNING SUM OF SEDIMENT IN CLASSES THAT HAVE
C              NOT EXCEEDED SEDMAX
C     IIFLAG - FLAG TO INDICATE IF REPROPORTIONING AMONG
C              CLASSES SHOULD BE CALCULATED
C     GADD   - ADDITIONAL SEDIMENT LOAD ADDED TO PARTICLE
C              CLASS I DURING REPORPORTIONING
C     SSASED - SPECIFIC SURFACE AREA FOR PARTICLE CLASS I IN
C              THE SEDIMENT
C     SSASOL - TOTAL SPECIFIC SURFACE AREA FOR THE INSITU
C              SOIL ON CURRENT PLANE
C     I      - COUNTER VARIABLE USED TO INDICATE PARTICLE
C              CLASS
C
C     + + + SUBROUTINES CALLED + + +
C
C     UNDFLO
C
C     BEGIN SUBROUTINE ENRICH
C
C     CHANGE TO COMPUTATION OF BETA MADE TO BE CONSISTENT WITH SIMILAR 
C     COMPUTATION IN SR PARAM
C
C     SET BETA VALUE TO 0.5 - ASSUME THESE COMPUTATIONS ARE ALWAYS
C     UNDER RAINFALL AND SHALLOW FLOW CONDITIONS
C
      BETA = 0.5
C     
      SUMSSA = 0.0
      SUMG = 0.0
C     
C     THE SPECIFIC SURFACE AREA VALUES FOR SAND, SILT, CLAY,
C     AND ORGANIC CARBON ARE THOSE USED IN THE CREAMS MODEL,
C     THE VALUES GIVEN BELOW HAVE UNITS OF (M^2)/G
C     
      SSASND = 0.05
      SSASLT = 4.0
      SSACLY = 20.0
      SSAORG = 1000.0
C     
C     AT THE BEGINNING OF A DEPOSITIONAL SECTION (OR THE LAST TIME
C     THROUGH AT THE END OF A PLANE), COMPUTE THE FRACTION OF EACH
C     PARTICLE TYPE USING A WEIGHTED AVERAGE OF SEDIMENT INPUTS
C     FROM LAST DEPOSITIONAL REGION AND THE EROSIONAL REGION BETWEEN
C     
      IF (LDTOP.GT.0.00001.AND.QOUT.GT.0.0) THEN
         INTLOD = THETA * (XTOP-XDETST)
         RILLOD = LDTOP - LDDEND - INTLOD
         IF (RILLOD.LT.0.0) RILLOD = 0.0
C        
         DO I = 1, NPART
            FRCFLW(I) = (FRCFLW(I)*LDDEND+FRAC(I)*
     1          RILLOD+FIDEL(I)*INTLOD) / LDTOP
         END DO
      END IF
C     
C     DETERMINE IF THIS IS THE LAST CALL AT THE END OF A PLANE 
C     (IENDFG=1)
C     
      IF (IENDFG.NE.0) THEN
C        
         DO I = 1, NPART
            IF (QOUT.LE.0.0) FRCFLW(I) = 0.0
C           
C           CALCULATE THE SPECIFIC SURFACE AREA OF THE SEDIMENT
C           
            SSASED = FRCFLW(I) * ((FRSND(I)*SSASND +
     1          FRSLT(I)*SSASLT + FRCLY(I)*SSACLY) / (1.0 + FRORG(I))
     1          + FRORG(I)*SSAORG/1.73)
            SUMSSA = SUMSSA + SSASED
         END DO
C        
C        CALCULATE THE SPECIFIC SURFACE AREA OF THE SURFACE SOIL
C        FOR THE CURRENT PLANE
C        
         SSASOL = (ORGMAT(1)*SSAORG/1.73) + (SAND(1)*SSASND + 
     1            SILT(1)*SSASLT + CLAY(1)*SSACLY) / (1.0 + ORGMAT(1))
C        
C        CALCULATE AN ENRICHMENT RATIO OF THE SPECIFIC SURFACE AREA
C        
         ENRATO = SUMSSA / SSASOL + 0.005
C     
      ELSE
C        
C        IF THERE IS WATER FLOWING OFF OF THE OVERLAND FLOW ELEMENTS,
C        THEN CALCULATE THE PARTICLE SORTING AND ENRICHMENT RATIO
C        (CASE 2 AND 3 HYDROLOGIC PLANES)
C        
         IF (QOUT.GT.0.0) THEN
            PKRO = (QOUT-QIN) / SLPLEN
C           
C           PROPORTION TRANSPORT CAPACITY TO THE INDIVIDUAL SIZE 
C           CLASSES AND CALCULATE THE SEDIMENT LOAD AT THE END OF THE 
C           DEPOSITIONAL REGION FOR EACH SIZE CLASS
C           
            TMPVR2 = XBOT + QOSTAR
            TMPVR3 = XTOP + QOSTAR
            TMPVR4 = TMPVR2 ** 2
            TMPVR5 = TMPVR3 ** 2
C           
            IF (ABS(PKRO).GT.1E-15) THEN
               PHIFLG = 1
            ELSE IF (QOSTAR.GE.0.0) THEN
               PHIFLG = 2
            ELSE
               PHIFLG = 3
            END IF
C           
            DO I = 1, NPART
               TMPVR1 = KTRATO * TCF1(I)
               AA = TMPVR1 * AINFTC(KK)
               BB = TMPVR1 * BINFTC(KK)
               CC = TMPVR1 * CINFTC(KK)
               FTHETA(I) = FIDEL(I) * THETA
               GU(I) = FRCFLW(I) * LDTOP
C              
               IF (PHIFLG.EQ.1) THEN
                  PHI = BETA * FALL(I) / PKRO
                  IF (PHI.GT.100000.) PHI = 100000.
                  IF (PHI.LT.-100000.) PHI = -100000.
               ELSE IF (PHIFLG.EQ.2) THEN
                  PHI = 100000.
               ELSE
                  PHI = -100000.
               END IF
C              
               RATIO = TMPVR3 / TMPVR2
C              
               IF (QOSTAR.GE.0.0.AND.RATIO.GT.1.0) RATIO = 1.0
               EXPON = PHI
               RATIO2 = RATIO
               CALL UNDFLO(RATIO2,EXPON)
C              
               COEF1 = PHI * AA / (PHI+2.0)
               COEF2 = (PHI*BB+FTHETA(I)-2.0*AA*PHI*QOSTAR) / (1.0+PHI)
               TERM1 = COEF1 * TMPVR4
               TERM2 = COEF2 * TMPVR2
               TERM3 = AA * QOSTAR ** 2 - BB * QOSTAR + CC
C              
               TERM4A = RATIO2 ** EXPON
               IF (TERM4A.LT.1.0E-08) TERM4A = 0.0
               TERM4B = GU(I) - COEF1 * TMPVR5 - COEF2 * TMPVR3 - TERM3
               GEND(I) = TERM1 + TERM2 + TERM3 + TERM4A * TERM4B
               IF (GEND(I).LT.0.0) GEND(I) = 0.0
               SUMG = SUMG + GEND(I)
C           
            END DO
C           
C           CORRECTION ADDED IF ENRICHMENT ROUTINE CALCULATES THAT 
C           THERE IS NO LOAD AT ALL AT END OF REGION - MUST STILL 
C           PROVIDE A SIZE DISTRIBUTION IN ORDER TO AGREE WITH OTHER 
C           PART OF MODEL CALCULATIONS THAT PREDICT A SEDIMENT LOAD
C           
C           THIS LIKELY WILL ONLY HAPPEN WHEN TRANSPORT CAPACITY
C           IS ZERO AND THERE IS NO INTERRILL DETACHMENT ON THE PLANE -
C           IN THIS CASE RETURN TO SR ROUTE AND ASSUME THAT THE 
C           PARTICLE SIZE DISTRIBUTION EXITING THE DEPOSITION REGION 
C           IS THE SAME THAT ENTERED
C           
            IF (SUMG.GT.0.0) THEN
C              
C              ADJUST THE INDIVIDUAL FRACTION SEDIMENT LOADS AT
C              THE END OF THE SECTION SO THAT THEY TOTAL TO THE
C              LOAD COMPUTED IN THE DEPOSITION ROUTINES ELSEWHERE
C              IN THE MODEL
C              
C              ALSO, COMPUTE THE MAXIMUM POSSIBLE SEDIMENT LOAD IN A 
C              PARTICLE CLASS WHICH IS THE SUM OF THE SEDIMENT 
C              ENTERING AT THE TOP (GU(I)) PLUS THE INTERRILL 
C              CONTRIBUTION (FTHETA(I)*(XBOT-XTOP))
C              
               DO I = 1, NPART
                  GEND(I) = GEND(I) * LDBOT / SUMG
                  SEDMAX(I) = GU(I) + FTHETA(I) * (XBOT-XTOP)
                  IF (GEND(I).LT.1.0E-15) GEND(I) = 1.0E-15
               END DO
C              
C              CHECK THAT THE MASS OF SEDIMENT IN ANY PARTICLE CLASS 
C              DOES NOT EXCEED THE TOTAL POSSIBLE MASS IN THAT CLASS 
C              WHICH IS THE SUM OF THE SEDIMENT ENTERING THE SEGMENT 
C              AT THE TOP (GU(I)) PLUS THE DETACHED INTERRILL SEDIMENT
C              (FTHETA(I)*(XBOT - XTOP)) - IF IT DOES THEN SET THE MASS
C              IN THE CLASS TO SEDMAX, AND THEN REPROPORTION THE
C              LEFTOVER MASS TO THE REMAINING PARTICLE CLASSES
C              
   10          RATBOT = 0.0
               SUMG = 0.0
               IIFLAG = 0
C              
               DO I = 1, NPART
                  IF (GEND(I).GT.SEDMAX(I)) THEN
                     GEND(I) = SEDMAX(I)
                     IIFLAG = 1
                  ELSE IF (GEND(I).LT.SEDMAX(I)) THEN
                     RATBOT = RATBOT + GEND(I)
                  END IF
                  SUMG = SUMG + GEND(I)
               END DO
C              
C              IF AT LEAST ONE OF THE PARTICLE CLASSES HAS BEEN
C              SET WITH GEND(I) = SEDMAX(I) THEN THE OTHER CLASSES THAT
C              HAVE NOT BEEN SET GEND(I) = SEDMAX(I) ARE REPROPORTIONED
C              
               IF (IIFLAG.NE.0) THEN
                  DO I = 1, NPART
                     IF (GEND(I).LT.SEDMAX(I)) THEN
                        GADD = (LDBOT-SUMG) * GEND(I) / RATBOT
                        GEND(I) = GEND(I) + GADD
                     END IF
                  END DO
               END IF
C              
               IF (IIFLAG.NE.0) GO TO 10
C              
C              COMPUTE FRACTION AT THE END OF THE DEPOSITIONAL REGION
C              
               IF (SUMG.GT.0.0) THEN
                  DO I = 1, NPART
                     FRCFLW(I) = GEND(I) / SUMG
                  END DO
               ELSE
                  DO I = 1, NPART
                     FRCFLW(I) = 0.0
                  END DO
               END IF
C           
            END IF
C        
C        IF FLOW ENDS ON THE PLANE (NO OUTFLOW), SET ALL FRACTIONS 
C        TO ZERO SINCE NO SEDIMENT IS LEAVING (CASE 4 HYDROLOGIC 
C        PLANE)
C        
         ELSE
            DO I = 1, NPART
               FRCFLW(I) = 0.0
            END DO
C        
         END IF ! IF (QOUT.GT.0.0) THEN
C     
      END IF    ! IF (IENDFG.NE.0) THEN 
C     
      RETURN
      END
