      SUBROUTINE EPRINT(SLPLEN,AVGSLP,RUNOFF,PEAKRO,EFFDRN,EFFLEN,
     1    EFFINT,EFFDRR)
C
C     + + + PURPOSE + + +
C     OPEN THE STANDALONE OUTPUT FILE.
C     PRINT OUT THE FILE HEADER AND THE
C     INPUT HYDROLOGY AND SLOPE PARAMETERS
C
C     CALLED FROM SUBROUTINE MAIN
C     AUTHOR(S): D. FLANAGAN
C
C     VERSION: THIS MODULE BASED ON WEPP V2004.7 PRINT.FOR
C     DATE CODED:  9-30-2004
C     CODED BY: D. FLANAGAN
C
C     + + + ARGUMENT DECLARATIONS + + +
C
      REAL SLPLEN, AVGSLP, RUNOFF, PEAKRO, EFFDRN,
     1     EFFLEN, EFFINT, EFFDRR
C
C     + + + ARGUMENT DEFINITIONS + + +
C
C     SLPLEN - SLOPE LENGTH OF CURRENT OFE (M)
C     AVGSLP - AVERAGE SLOPE OF A LINE PASSING THROUGH ENDPOINTS
C              OF THE CURRENT OFE (M/M)
C     RUNOFF - RUNOFF DEPTH (M)
C     PEAKRO - PEAK RUNOFF RATE (M/S)
C     EFFDRN - EFFECTIVE DURATION OF RUNOFF (S)
C     EFFLEN - EFFECTIVE LENGTH OF RUNOFF (M)
C     EFFINT - EFFECTIVE RAINFALL INTENSITY (M/S)
C     EFFDRR - EFFECTIVE DURATION OF RAINFALL (S)
C
C     + + + LOCAL VARIABLES + + +
C
C     INTEGER IHILL
C
C     + + + LOCAL DEFINITIONS + + +
C
C     IHILL  - CURRENT HILLSLOPE PROFILE IN A WATERSHED SIMULATION
C
C     + + + END SPECIFICATIONS + + +
C
C
C*********************************************************************
C
C     IF THE FIRST OFE, OPEN THE OUTPUT FILE AND PRINT THE 
C     HEADER INFORMATION.
C
      WRITE (8,1000)
      WRITE (8,1100)
      WRITE (8,*)
C     
C     IHILL = 1
C     WRITE (8,1200) IHILL
C     WRITE (8,1300)
C     WRITE (8,1400) IPLANE
      WRITE (8,1500)
      WRITE (8,1600) SLPLEN, AVGSLP
      WRITE (8,1700) RUNOFF * 1000., PEAKRO * 3.6E6, 
     1    EFFDRN / 60., EFFLEN, EFFINT * 3.6E6, EFFDRR / 60.
      WRITE (8,1800)
C     
      RETURN
 1000 FORMAT (/,' (WEPP) EROSION STAND-ALONE OUTPUT ',//)
 1100 FORMAT (//'I.   SINGLE STORM HYDROLOGY',/,2X,9('-'),1X,5('-'),1X,
     1    36('-'))
C1200 FORMAT (//2X,18('*'),/4X,'HILLSLOPE ',I2,/,2X,18('*'))
C1300 FORMAT (//6X,27('*'))
C1400 FORMAT (7X,'OVERLAND FLOW ELEMENT ',I2)
 1500 FORMAT (6X,27('*'))
 1600 FORMAT (/'  INPUT RUNOFF PARAMETERS'/2X,52('-')/
     1    '      PLANE LENGTH               ',F8.2,' (M)'/
     1    '      AVERAGE SLOPE OF PROFILE   ',F8.3/)
 1700 FORMAT (/'  RUNOFF INPUT'/2X,52('-')/
     1    '      RUNOFF DEPTH               ',F8.2,' (MM)'/
     1    '      PEAK RUNOFF RATE           ',F8.2,' (MM/HR)'/
     1    '      EFFECTIVE RUNOFF DURATION  ',F8.2,' (MIN)'/
     1    '      EFFECTIVE LENGTH           ',F8.2,' (METERS)'/
     1    '      EFFECTIVE INTENSITY        ',F8.2,' (MM/HR)'/
     1    '      EFFECTIVE RAINFALL DURATION',F8.2,' (MIN)'/)
 1800 FORMAT (2X,52('-'))
      END
