      REAL FUNCTION FALVEL(SPG,DIA)
C
C     FUNCTION FALVEL RETURNS THE FALL VELOCITY FOR A SPECIFIC SIZE  
C     CLASS PARTICLE GIVEN SPECIFIC GRAVITY (SPG), DIAMETER (DIA), 
C     KINEMATIC VISCOSITY OF THE WATER (KINVIS), AND ACCELERATION
C     OF GRAVITY (ACCGAV)
C
C     MODULE ADAPTED FROM WEPP VERSION 2004.7 AND CALLED FROM THE
C     MAIN PROGRAM
C
C     AUTHOR(S): D.C FLANAGAN AND J.C. ASCOUGH II
C     DATE LAST MODIFIED: 10-12-2004
C
C     + + + ARGUMENT DECLARATIONS + + +     
C
      REAL SPG, DIA
C      
C     + + + ARGUMENT DEFINITIONS + + +     
C             
C     SPG - SPECIFIC GRAVITY
C     DIA - PARTICLE SIZE DIAMETER
C
C     + + + LOCAL DECLARATIONS + + + 
C                          
      REAL KINVIS, ACCGAV, RTSID, REY, CDRE(9), CDRE2(9)
      INTEGER I
C
C     + + + LOCAL VARIABLE DEFINITIONS + + + 
C
C     + + + DATA INITIALIZATIONS + + +
C
C     BEGIN FUNCTION FALVEL
C
      DATA CDRE /-6.90775, -4.60517, -2.30258, 0.0, 2.30258, 4.60517, 
     1    6.90775, 9.21034, 11.51292/
      DATA CDRE2 / -4.50986, -1.51413, 0.78846, 3.12676, 6.04025, 
     1    9.30565, 13.08154, 17.50439, 22.29188/
C
      KINVIS = 1.0E-06
      ACCGAV = 9.807
C     
C     DIMENSIONLESS PARAMETER (RTSID=CD*REY*REY) FOR DRAG COEFFIENT
C     
      RTSID = ((SPG-1.0)*ACCGAV*(DIA**3)/(KINVIS**2)) * (8.0/6.0)
C     
C     COMPUTE FALVEL FROM TABLED VALUES FOR LARGER PARTICLES
C     
      IF (RTSID.GE.0.024) THEN
         RTSID = ALOG(RTSID)
         DO I = 2, 9
            IF (CDRE2(I).GT.RTSID) THEN
               REY = EXP((RTSID-CDRE2(I-1))/(CDRE2(I)-CDRE2(I-1))*(
     1             CDRE(I)-CDRE(I-1))+CDRE(I-1))
               FALVEL = REY * KINVIS / DIA
               RETURN
            END IF
         END DO
C        
C        TRAP VALUES WHICH ARE LARGER THAN TABLE VALUES
C        
         WRITE (6,*) ' CDRE2 OUT OF RANGE.  SPG=', SPG, '   DIA=', DIA
C        
         FALVEL = EXP(CDRE(9)) * KINVIS / DIA
C     
C     FALVEL USING STOKES SOLUTION FOR SPHERES FOR SMALL PARTICLES
C     
      ELSE
         FALVEL = ((DIA**2)*(SPG-1.0)*(ACCGAV)) / (KINVIS*18.0)
      END IF
C     
      RETURN
C     
      END
