      SUBROUTINE INPUT(RSPACE,WIDTH,RUNOFF,PEAKRO,EFFDRN,EFFINT,EFFDRR,
     1    NPART,FRAC,DIA,SPG,FRCLY,FRSLT,FRSND,FRORG,SAND,SILT,CLAY,
     1    ORGMAT,KIADJ,KRADJ,SHCRTADJ,FRCSOL,FRCTRL,RRC,FWIDTH,EFFLEN,
     1    QOUT, QSOUT)
C
C     SUBROUTINE INPUT READS IN VALUES REQUIRED TO PERFORM EROSION
C     CALCULATIONS FOR THE STANDALONE EROSION MODEL
C
C     MODULE ADAPTED FROM WEPP VERSION 2004.7 AND CALLED FROM THE
C     MAIN PROGRAM
C
C     AUTHOR(S): D.C FLANAGAN AND J.C. ASCOUGH II
C     DATE LAST MODIFIED: 4-1-2005
C
C     + + + PARAMETER DECLARATIONS + + + 
C
      INTEGER MXPART, MXNSL
      PARAMETER (MXPART = 10,MXNSL = 10)
C
C     + + + ARGUMENT DECLARATIONS + + +     
C
      REAL RSPACE, WIDTH, RUNOFF, PEAKRO, EFFDRN, EFFINT, EFFDRR,
     1    FRAC(MXPART), DIA(MXPART), SPG(MXPART), FRCLY(MXPART), 
     1    FRSLT(MXPART), FRSND(MXPART), FRORG(MXPART), SAND(MXNSL),
     1    SILT(MXNSL), CLAY(MXNSL), ORGMAT(MXNSL), KIADJ, KRADJ, 
     1    SHCRTADJ, FRCSOL, FRCTRL, RRC, FWIDTH, EFFLEN, QOUT, QSOUT
      INTEGER NPART
C
C     + + + ARGUMENT DEFINITIONS + + +         
C
C     BEGIN SUBROUTINE INPUT
C
C     READ THE FLOW DISCHARGE OUT OF THE PREVIOUS ELEMENT
C     (IF ONE EXISTS) AND THE SEDIMENT DISCHARGE OUT OF 
C     THE PREVIOUS ELEMENT.  THESE BECOME THE TOP BOUNDARY
C     CONDITIONS FOR THE CURRENT ELEMENT.   DCF  4-6-05
      READ (7,*) QOUT, QSOUT
      IF (QOUT.LE.0.0)QSOUT = 0.0
C
C     READ THE NUMBER OF PARTICLE SIZE CLASSES, FIELD WIDTH,
C     AND SPECIFIC GRAVITY OF EACH PARTICLE CLASS
C     
      READ (7,*) NPART, FWIDTH
      READ (7,*) (SPG(K),K = 1,NPART)
C     
C     READ THE RILL SPACING (M), RILL WIDTH (M), AND EFFECTIVE
C     PLANE LENGTH FROM THE STANDARD EROSION INPUT FILE.
C
      READ (7,*) RSPACE, WIDTH, EFFLEN
C
C     READ THE RUNOFF DEPTH (M), PEAK RUNOFF RATE (M^3/S), 
C     EFFECTIVE RUNOFF DURATION (S), EFFECTIVE RAINFALL INTENSITY (M/S),
C     EFFECTIVE DURATION OF RAINFALL EXCESS (S) FROM THE PASS FILE
C     CREATED BY THE HYDROLOGY MODULE.
C           
      READ (3,*) RUNOFF, PEAKRO, EFFDRN, EFFINT, EFFDRR
C     
C     READ THE FRACTION OF EACH PARTICLE CLASS (O-1), DIAMETER OF
C     EACH PARTICLE CLASS (MM), AND THE FRACTION OF CLAY (0-1),
C     SILT (0-1), SAND (0-1), AND ORGANIC MATTER (0-1) IN EACH
C     PARTICLE CLASS
C     
      READ (7,*) (FRAC(J),J = 1,NPART)
      READ (7,*) (DIA(J),J = 1,NPART)
      READ (7,*) (FRSND(J),J = 1,NPART)
      READ (7,*) (FRSLT(J),J = 1,NPART)
      READ (7,*) (FRCLY(J),J = 1,NPART)
      READ (7,*) (FRORG(J),J = 1,NPART)
C     
C     READ THE FRACTION OF CLAY (0-1), SILT (0-1), SAND (0-1), AND
C     ORGANIC MATTER (0-1) IN THE FIRST SOIL LAYER
C     
      READ (7,*) SAND(1), SILT(1), CLAY(1), ORGMAT(1)
C     
C     READ THE ADJUSTED INTERILL DETACHMENT RATE PARAMETER
C     (KG/S/M^4), ADJUSTED RILL DETACHMENT RATE PARAMETER (S/M),
C     ADJUSTED CRITICAL SHEAR STRESS (KG/M/S^2), SOIL GRAIN FRICTION
C     FACTOR, TOTAL RILL FRICTION FACTOR, AND THE RANDOM ROUGHNESS
C     COEFFICIENT
C     
      READ (7,*) KIADJ, KRADJ, SHCRTADJ, FRCSOL, FRCTRL, RRC
C     
      RETURN
      END
