      PROGRAM MAIN
C
C     THIS PROGRAM IS THE MAIN DRIVER FOR AN OMS-BASED STANDALONE
C     EROSION COMPONENT BASED ON THE WEPP V2004.7 EROSION CODE
C
C     AUTHORS: DCF, JCAII   SEPTEMBER 2004
C
C     DATE LAST MODIFIED:  4-1-2005
C
C     + + + PARAMETER DECLARATIONS + + +
C
      INTEGER MXPART, MXNSL, MXSLP
      PARAMETER (MXPART = 10,MXNSL = 10,MXSLP = 40)
C
      REAL RSPACE, WIDTH, RUNOFF, PEAKRO, EFFDRN, EFFINT, 
     1    EFFDRR, FRAC(MXPART), DIA(MXPART), SPG(MXPART), 
     1    FRCLY(MXPART), FRSLT(MXPART), FRSND(MXPART), FRORG(MXPART), 
     1    SAND(MXNSL), SILT(MXNSL), CLAY(MXNSL), ORGMAT(MXNSL), 
     1    KIADJ, KRADJ, SHCRTADJ, FRCSOL, FRCTRL, RRC
C
      REAL SLPLEN, XINPUT(101), Y(101), AVGSLP, A(MXSLP), B(MXSLP), 
     1    XL(MXSLP), XU(MXSLP), TOTLEN
C
      REAL EFFLEN, QIN, QOUT, QOSTAR, AINF(MXSLP), BINF(MXSLP),
     1    CINF(MXSLP), AINFTC(MXSLP), BINFTC(MXSLP), CINFTC(MXSLP), 
     1    QSHEAR, SHRSOL, TCEND, STRLDN
C
      REAL FALVEL, FALL(MXPART), EATA, TAUC, THETA, PHI
C
      REAL QSOUT, FWIDTH, AVSOLE, KTRATO, LOAD(101), IRDGDX, 
     1    SLPEND, FIDEL(MXPART), TCF1(MXPART), ENRATO, FRCFLW(MXPART),
     1    DSLOST(100)
C
      INTEGER NPART, NSLPTS, I, J
C
C     BEGIN PROGRAM MAIN
C
C     OPEN INPUT/OUTPUT FILES
C
      OPEN (UNIT=3,FILE='HYD2ER.PAS',STATUS='OLD')
      OPEN (UNIT=7,FILE='EROSION.INP',STATUS='OLD')
      OPEN (UNIT=8,FILE='EROSION.OUT',STATUS='UNKNOWN')
      OPEN (UNIT=9,FILE='EROPLOT.OUT',STATUS='UNKNOWN')
C
C     INITIALIZE VARIABLES 
C
      QOUT = 0.0
      QSOUT = 0.0
C    
C     CALL INPUT SUBROUTINE TO READ IN VALUES REQUIRED TO PERFORM
C     EROSION CALCULATIONS
C        
      CALL INPUT(RSPACE,WIDTH,RUNOFF,PEAKRO,EFFDRN,EFFINT,EFFDRR,
     1           NPART,FRAC,DIA,SPG,FRCLY,FRSLT,FRSND,FRORG,SAND,SILT,
     1           CLAY,ORGMAT,KIADJ,KRADJ,SHCRTADJ,FRCSOL,FRCTRL,RRC,
     1           FWIDTH,EFFLEN,QOUT,QSOUT)
C        
C     CALL SLOPE PROFILE SUBROUTINE TO COMPUTE THE SLOPE COEFFICIENTS
C        
      CALL PROFIL(A,B,AVGSLP,NSLPTS,SLPLEN,XINPUT,XU,XL,Y,TOTLEN)
C        
C     COMPUTE BOUNDARY CONDITIONS FOR TOP OF PLANE BEFOREHAND
C     CODE EXTRACTED AND MODIFIED FROM WEPP 2004.7 XINFLO.FOR
C        
      CALL XINFLO(XINPUT,EFFLEN,SLPLEN,A,B,QIN,QOUT,PEAKRO,QOSTAR,
     1            AINF,BINF,CINF,AINFTC,BINFTC,CINFTC,QSHEAR,RSPACE,
     1            NSLPTS)
C        
C     GET FALL VELOCITIES FOR THE INPUT PARTICLE SIZE
C     CLASSES (FROM SUBROUTINE PRTCMP)
C        
C     CONVERT INPUT VALUES FOR PARTICLE DIAMETERS FROM MM TO M
C     CALL FUNCTION FALVEL TO CALCULATE THE FALL VELOCITIES
C        
      DO I = 1, NPART
         DIA(I) = DIA(I) / 1000.0
         FALL(I) = FALVEL(SPG(I),DIA(I))
      END DO
C        
C     CALL PARAM SUBROUTINE TO CALCULATE THE NONDIMENSIONAL PARAMETER
C     VALUES TO USE IN THE EROSION CALCULATIONS.
C        
      CALL PARAM(QIN,QOUT,QOSTAR,QSHEAR,QSOUT,A,B,AVGSLP,WIDTH,RSPACE,
     1       KTRATO,SHRSOL,TCEND,FRCSOL,FRCTRL,RRC,NPART,FRAC,DIA,SPG,
     1       FALL,RUNOFF,EFFDRN,EFFINT,EFFDRR,STRLDN,TCF1,FIDEL,EATA,
     1       TAUC,THETA,PHI,SLPEND,AINF,BINF,CINF,AINFTC,BINFTC,CINFTC,
     1       SAND,SLPLEN,KIADJ,KRADJ,SHCRTADJ,NSLPTS,EFFLEN)
C        
C     CALL THE EROSION ROUTING SUBROUTINE ROUTE.
C     THIS IS LARGELY TAKEN FROM WEPP V2004.7  DCF
C     ONLY DO EROSION CALCULATIONS IF THERE IS RUNON OR RUNOFF 
C     FROM THE HILLSLOPE ELEMENT.
C
      IF (QIN.GT.0.0 .OR. QOUT.GT.0.0)THEN
        CALL ROUTE(QIN,QOUT,QOSTAR,STRLDN,KTRATO,AINF,BINF,CINF,
     1             AINFTC,BINFTC,CINFTC,NPART,FRAC,FRCLY,FRSLT,FRSND,
     1             FRORG,FALL,FRCFLW,NSLPTS,XINPUT,XU,XL,LOAD,ENRATO,
     1             TCF1,FIDEL,SAND,SILT,CLAY,ORGMAT,EATA,TAUC,THETA,
     1             PHI,SLPLEN)
C        
C       CALL THE SLOSS SUBROUTINE TO REDIMENSIONALIZE THE
C       SEDIMENT LOAD AT POINT OUTPUT FROM ROUTE, AND 
C       COMPUTE THE DG/DX VALUES AT THE POINTS AND SEDIMENT
C       LEAVING THE PROFILE.
C        
        CALL SLOSS(LOAD,TCEND,WIDTH,RSPACE,EFFDRN,THETA,SLPLEN,IRDGDX,
     1             QSOUT,DSLOST,AVSOLE,QOUT)
C
C       FOLLOWING ADDED TO CORRECT ERROR AT OFE BREAK BETWEEN
C       A CASE 4 OFE AND A CASE 2 OFE.  DCF 1-21-2005
C
        IF(QOUT.LE.0.0)QSOUT = 0.0
C
      ELSE
C
C       NO RUNON OR RUNOFF FOR THE OFE, THEN SET SOIL LOSS,
C       SEDIMENT, PARTICLE AND ENRICHMENT OUTPUTS TO ZERO.
C
        DO J = 2, 101
          DSLOST(J-1) = 0.0
        END DO
        DO J = 1, NPART
          FRCFLW(J) = 0.0
        END DO
        IRDGDX = 0.0
        ENRATO = 0.0
        AVSOLE = 0.0
        QSOUT = 0.0
      ENDIF      
C        
C     CALL THE PRINT SUBROUTINE TO OPEN THE OUTPUT FILE,
C     PRINT THE HEADER INFORMATION, AND PRINT THE HYDROLOGY
C     INPUT AS OUTPUTS.
C        
      CALL EPRINT(SLPLEN,AVGSLP,RUNOFF,PEAKRO,EFFDRN,EFFLEN,
     1            EFFINT,EFFDRR)
C        
C        
C      END DO
C
C     CALL THE SEDOUT SUBROUTINE TO DETERMINE THE DETACHMENT AND
C     DEPOSITION REGIONS AND INFORMATION, AND WRITE OUTPUTS.
C        
      CALL SEDOUT(IRDGDX,DSLOST,AVSOLE,ENRATO,NPART,FRAC,DIA,SPG,
     1            FRCLY,FRSLT,FRSND,FRORG,FRCFLW,SLPLEN,FWIDTH,AVGSLP,
     1            Y,TOTLEN)
C     
C     CLOSE INPUT/OUTPUT FILES
C     
      CLOSE (3)
      CLOSE (7)
      CLOSE (8)
      CLOSE (9)
C     
      STOP
      END
