      SUBROUTINE ROOT(A,B,C,X1,X2)
C
C     SUBROUTINE ROOT FINDS ROOTS FOR THE EQUATION Y=A*X**2+B*X+C
C
C     MODULE ADAPTED FROM WEPP VERSION 2004.7 AND CALLED FROM 
C     SUBROUTINE XCRIT
C
C     AUTHOR(S): D.C. FLANAGAN AND J.C. ASCOUGH II
C     DATE MODIFIED:  9-30-2004
C
C     + + + ARGUMENT DECLARATIONS + + +
C
      REAL A, B
      DOUBLE PRECISION C, X1, X2
C
C     + + + ARGUMENT DEFINITIONS + + +
C
C     A  - COEFFICIENT FOR X^2 IN QUADRATIC EQUATION
C     B  - COEFFICIENT FOR X IN QUADRATIC EQUATION
C     C  - CONSTANT IN QUADRATIC EQUATION
C     X1 - ONE OF TWO ROOT SOLUTIONS FOR QUADRATIC EQUATION
C     X2 - ONE OF TWO ROOT SOLUTIONS FOR QUADRATIC EQUATION
C
C     + + + LOCAL VARIABLES + + +
C
      DOUBLE PRECISION CC, PART
      REAL B1, TMPVR1
C
C     CC - 
C     PART - 
C     B1 - 
C     TMPVR1 - 
C
C     + + + LOCAL VARIABLE DEFINITIONS + + +
C
C     BEGIN SUBROUTINE ROOT
C
      B1 = -B
      TMPVR1 = 2.0 * A
      CC = -C
      PART = SQRT(B**2-4.0*A*CC)
      X1 = (B1-PART) / TMPVR1
      X2 = (B1+PART) / TMPVR1
C     
      IF (X1.GT.X2) THEN
         PART = X2
         X2 = X1
         X1 = PART
      END IF
C     
      RETURN
      END
