      SUBROUTINE SEDIST(DSLOST,DSTOT,STDIST,DELXX,SLPLEN,AVGSLP,
     1    Y,YSDIST)
C
C     + + + PURPOSE + + +
C     CREATES A REPRESENTATIVE HILLSLOPE PROFILE (SEDIMENT LOAD,
C     X-DISTANCE, DELTA-X) FROM OVERLAND FLOW ELEMENTS.
C
C     CALLED FROM SEDSEG
C     AUTHOR(S): D.C. FLANAGAN, J.C. ASCOUGH
C
C     VERSION: THIS MODULE MODIFIED FROM WEPP VERSION 2004.7
C     DATE MODIFIED: 9-30-2004
C     MODIFIED BY: D. FLANAGAN
C
C     + + + ARGUMENT DECLARATIONS + + +
C
      REAL DSLOST(100), DSTOT(1000), STDIST(1000), DELXX
      REAL SLPLEN, AVGSLP, Y(101), YSDIST(1000)
C
C
C     + + + ARGUMENT DEFINITIONS + + +
C
C     DSLOST - NET SOIL LOSS/GAIN AT EACH POINT DOWN ENTIRE
C     DSTOT  - SEDIMENT LOSS FOR EACH POITN DOWN HILLSLOPE (KG/M^2)
C     STDIST - DISTANCE DOWN HILLLSLOPE AT EACH POINT (M)
C     DELXX  - DELTA X INCREMENTS BETWEEN EACH POINT DOWN HILSLOPE (M)
C     SLPLEN - SLOPE LENGTH OF EACH OFE (M)
C     AVGLSP - AVERAGE SLOPE OF LINE PASSING THROUGH ENDPOINTS
C              OF AN OFE  (M/M)
C     Y      - VERTICAL DISTANCE OF EACH POINT ON PROFILE (M)
C
C     + + + LOCAL VARIABLES + + +
C
      REAL XDIST(101), YDIST(101), DIST, YTOT
      INTEGER K, KK, LL
C
C     + + + LOCAL DEFINITIONS + + +
C     XDIST  -
C     YDIST  -
C     DIST   -
C     YTOT   -
C     I      -
C     J      -
C     K      -
C     KK     -
C     LL     -
C
C     + + + END SPECIFICATIONS + + +
C
C
      KK = 0
      YTOT = 0.
C      IF (NPLANE.GT.1) THEN
C        DO 10 I = 2, NPLANE
C           YTOT = YTOT + SLPLEN(I) * AVGSLP(I)
C  10    CONTINUE
C     END IF
C     
C     DO 40 I = 1, NPLANE
C        
         DELXX = SLPLEN / 100.0
C        
         DO 30 K = 2, 101
            LL = K - 1
            DIST = 0.0
C           DO 20 J = 1, I
C              IF (I.NE.J) THEN
C                 DIST = SLPLEN(I-J) + DIST
C              END IF
C  20       CONTINUE
            YDIST(K) = YTOT + SLPLEN * AVGSLP * Y(K)
            XDIST(K) = DIST + (SLPLEN/100.0) * FLOAT(K-1)
            KK = KK + 1
            DSTOT(KK) = DSLOST(LL)
            STDIST(KK) = XDIST(K)
            YSDIST(KK) = YDIST(K)
   30    CONTINUE
C        IF (I.NE.NPLANE) YTOT = YTOT - SLPLEN(I+1) * AVGSLP(I+1)
C  40 CONTINUE
C     
      RETURN
      END
