      SUBROUTINE SEDOUT(IRDGDX,DSLOST,AVSOLE,ENRATO,NPART,FRAC,
     1    DIA,SPG,FRCLY,FRSLT,FRSND,FRORG,FRCFLW,SLPLEN,FWIDTH,AVGSLP,
     1    Y,TOTLEN)
C
C     + + + PURPOSE + + +
C     CONTROLS THE PRINTING OF OUTPUT.
C     PLACES DETACHMENT AND DEPOSITION OUTPUT DATA IN COLUMN FORM.
C
C     CALLED FROM SUBROUTINE CONTIN
C     AUTHOR(S): D. FLANAGAN AND J. ASCOUGH
C
C     VERSION: THIS MODULE MODIFIED FROM WEPP V2004.7 CODE
C     DATE LAST MODIFIED:  4-1-2005
C
C     + + + PARAMETER DECLARATIONS + + +
C
      INTEGER MXPART
      PARAMETER (MXPART = 10)
C
C     + + + ARGUMENT DECLARATIONS + + +
C
      INTEGER NPART
      REAL IRDGDX, DSLOST(100), AVSOLE, ENRATO, FRAC(MXPART),
     1     DIA(MXPART), SPG(MXPART), FRCLY(MXPART), FRSLT(MXPART), 
     1     FRSND(MXPART), FRORG(MXPART), FRCFLW(MXPART), SLPLEN,
     1     FWIDTH, AVGSLP
      REAL Y(101), TOTLEN
C
C     + + + ARGUMENT DEFINITIONS + + +
C
C     NPART  - NUMBER OF PARTICLE SIZE CLASSES
C     IRDGDX - INTERRILL CONTRIBUTION TO DG/DX) IN (KG/M^2)
C     DSLOST - NET SOIL LOSS/GAIN AT EACH POINT ON HILLSLOPE FOR
C              A STORM EVENT (TIME*DG/DX) - (KG/M**2)
C     AVSOLE - STORM SEDIMENT LOSS (KG/M)
C     ENRATO - ENRICHMENT RATIO OF SPECIFIC SURFACE AREA OF SEDIMENT
C     FRAC   - FRACTION OF EACH PARTICLE CLASS AT POINT OF DETACHMENT
C     DIA    - DIAMETER OF PARTICLE CLASS (M)
C     SPG    - SPECIFIC GRAVITY OF PARTICLE CLASS
C     FRCLY  - FRACTION OF CLAY IN A PARTICLE CLASS
C     FRSLT  - FRACTION OF SILT IN A PARTICLE CLASS
C     FRSND  - FRACTION OF SAND IN A PARTICLE CLASS
C     FRORG  - FRACTION OF ORGANIC MATTER IN A PARTICLE CLASS
C     FRCFLW - FRACTION OF EACH PARTICLE TYPE IN FLOW
C     SLPLEN - SLOPE LENGTH OF AN OFE (M)
C     FWIDTH - FIELD WIDTH (M)
C
C
C     + + + LOCAL VARIABLES + + +
C
C     INTEGER IYEAR, ISUM, IEVT, IFOFE, NOOUT
      INTEGER IYEAR, NOOUT
      INTEGER I, J, JEND, JUN, NELEM1, NELEM2, NELEM3, M
      INTEGER NCOL1(10), NCOL2(10), NCOL3(10), NCOL4(10), NCOL11, 
     1    NCOL22, NCOL33, NCOL44, NFELEM(1000)
      REAL SS1, SS2, SS3, X1, X2, X3, MAREA
      REAL DSTOT(1000), YSDIST(1000), STDIST(1000)
C
C     + + + LOCAL DEFINITIONS + + +
C
C     IYEAR  - FLAG THAT INDICATES GETTING AVERAGE ANNUAL SUMMARIES
C              THROUGH SEDOUT ( SET IN CONTIN OR WSHDRV)
C     ISUM   - FLAG TO INDICATE IF THE INFORMATION SENT TO SEDOUT IS
C              SUPPOSED TO WRITE TO SUMMARY FILES
C              (0 - MEANS NO,  1 - MEANS YES )
C     IEVT   - FLAG TO INDICATE IF THE INFORMATION SENT TO SEDOUT IS
C              SUPPOSED TO WRITE TO EVENT LINE OUTPUT
C              SUMMARY FILES  (0 - MEANS NO,  1 - MEANS YES )
C     IFOFE   - FLAG TO INDICATE IF THE INFORMATION SENT TO SEDOUT IS
C              SUPPOSED ELEMENT LINE OUTPUT  (0 - NO; 1 - YES)
C     NOOUT  - FLAG INDICATING TYPE OF OUTPUT DESIRED
C                    0 - EVENT BY EVENT - NO SUMMARY FILES
C                    1 - EVENT BY EVENT - SUMMARY FILES
C                    2 - ALL OTHER OUTPUT - WITH SUMMARY OR GRAPHICS
C     I      - COUNTER VARIABLE
C     J      - COUNTER VARIABLE
C     JEND   - VALUE OF CUMULATIVE LAST POINT ON HILLSLOPE NUMBER
C     JUN    - OUTPUT UNIT NUMBER
C     NELEM1 -
C     NELEM2 -
C     NELEM3 -
C     M      - 
C     NCOL1  -
C     NCOL2  -
C     NCOL3  -
C     NCOL4  -
C     NCOL11 - 
C     NCOL22 -
C     NCOL33 -
C     NCOL44 -
C     NFELEM - NUMBER OF CUMULATIVE POINTS THROUGH OFES "J" UNITS LONG
C     M      -
C     X1     - SOIL LOSS AT POINT IN COLUMN ONE TO PRINT OUT
C     SS1    - DISTANCE AT POINT IN COLUMN ONE TO PRINT OUT
C     X2     - SOIL LOSS AT POINT IN COLUMN TWO TO PRINT OUT
C     SS2    - DISTANCE AT POINT IN COLUMN TWO TO PRINT OUT
C     X3     - SOIL LOSS AT POINT IN COLUMN THREE TO PRINT OUT
C     SS3    - DISTANCE AT POINT IN COLUMN THREE TO PRINT OUT
C     TOTLEN - TOTAL LENGTH OF THE HILLSLOPE PROFILE (M)
C
C     + + + END SPECIFICATIONS + + +
C
      CHARACTER*7 UNITS(13)
C
      DATA NCOL1 /10 * 1/
      DATA NCOL2 /35, 68, 101, 135, 168, 201, 235, 268, 301, 335/
      DATA NCOL3 /69, 135, 201, 269, 335, 401, 469, 535, 601, 669/
      DATA NCOL4 /33, 67, 101, 133, 167, 201, 233, 267, 301, 333/
      DATA NFELEM /100 * 1, 100 * 2, 100 * 3, 100 * 4, 100 * 5, 100 * 6,
     1    100 * 7, 100 * 8, 100 * 9, 100 * 10/
      DATA UNITS /'     MM', '  KG/M2', '    IN.', '    T/A', '    FT.',
     1    ' LBS/FT', '    LBS', '   KG/M', '      M', '     KG', 
     1    '   T/HA', '     HA', '  ACRES'/
C
C     TOTLEN = 0.0
C     DO 10 I = 1, NPLANE
C        TOTLEN = TOTLEN + SLPLEN(I)
C  10 CONTINUE
C     
C     
C     METRIC HILLSLOPE AREA
      MAREA = TOTLEN * FWIDTH
C     
C     DATA UNITS
C     1=MM
C     2=KG/M2
C     3=IN.
C     4=T/A
C     5=FT.
C     6=LBS/FT
C     7=LBS
C     8=KG/M
C     9=M
C     
C********************************************************************
C     
C     FOR NOW - SET IMODEL = 2 FOR SINGLE STORM SIMULATION.
C     SET FOR NO EVENT LINE OUTPUT (IEVT=0).
C     SET FOR NO SUMMARY OUTPUT (ISUM=0)
C     SET FOR SINGLE STORM OUTPUT (IOUTPT=1)
C     SET FOR EVENT BY EVENT OUTPUT WITH NO SUMMARY FILES (NOOUT=0)
C     SET FOR NO AVERAGE ANNUAL SUMMARY (IYEAR = 0)
C     SET FOR SINGLE STORM OUTPUT (IOUTSS = 0)
C     D. FLANAGAN 9-29-2004
C     
C     
C     IMODEL = 2
C     IEVT = 0
C     ISUM = 0
C     IOUTPT = 1
      NOOUT = 0
      IYEAR = 0
C     IOUTSS = 0
C     
C     JUN = 31
C     IF(IMODEL.EQ.2)JUN = 32
C     JUN = 32
      JUN = 8
C     
      NCOL11 = NCOL1(1)
      NCOL22 = NCOL2(1)
      NCOL33 = NCOL3(1)
      NCOL44 = NCOL4(1)
      JEND = 100
C     
C     CALL SEDSEG(DSLOST,JUN,IYEAR,NOOUT,AVEDET,MAXDET,PTDEP,
C     1            PTDET,AVEDEP,MAXDEP,PTMAX,PTMIN,DSTOT,STDIST,IRDGDX)
      CALL SEDSEG(DSLOST,JUN,IYEAR,NOOUT,DSTOT,STDIST,IRDGDX,YSDIST,
     1            AVGSLP,SLPLEN,Y)
C     
      WRITE (JUN,1100)
      WRITE (JUN,1200)
      WRITE (JUN,1300)
      WRITE (JUN,1400)
      WRITE (JUN,1500)
C     
      M = NCOL22 - 1
C     
      DO 30 I = 1, M
C        
         J = 0
C        
         DO 20 K = 1, JEND
C           
            J = J + 1
            IF (K.EQ.NCOL11) THEN
               X1 = DSTOT(K)
               SS1 = STDIST(K)
               NELEM1 = NFELEM(J)
            ELSE IF (K.EQ.NCOL22) THEN
               X2 = DSTOT(K)
               SS2 = STDIST(K)
               NELEM2 = NFELEM(J)
            ELSE IF (K.EQ.NCOL33) THEN
               X3 = DSTOT(K)
               SS3 = STDIST(K)
               NELEM3 = NFELEM(J)
            END IF
C        
   20    CONTINUE
C        
         IF (I.LT.NCOL44) THEN
            WRITE (JUN,1000) SS1, X1, NELEM1, SS2, X2, NELEM2, SS3, X3,
     1          NELEM3
         ELSE
            WRITE (JUN,1000) SS1, X1, NELEM1, SS2, X2, NELEM2
         END IF
C        
         NCOL11 = NCOL11 + 1
         NCOL22 = NCOL22 + 1
         NCOL33 = NCOL33 + 1
C     
   30 CONTINUE
C     
      WRITE (JUN,1600)
C     
      WRITE (JUN,1700)
C     
C     WRITE TO THE OUTPUT FILE THE SEDIMENT LEAVING THE PROFILE
C     IN KG/M, IN KG/M^2, AND IN TONNES/HA.
C     
      WRITE (JUN,1800) AVSOLE
      WRITE (JUN,1900) AVSOLE * FWIDTH, UNITS(10), FWIDTH, UNITS(9)
      WRITE (JUN,2000) (AVSOLE*FWIDTH*0.001) / (MAREA*0.0001), 
     1    UNITS(11), MAREA / 10000, UNITS(12)
C     
      WRITE (JUN,2100)
C     
      CALL ENRPRT(JUN,NPART,FRAC,FRCFLW,DIA,SPG,FRSND,FRSLT,
     1    FRCLY,FRORG,ENRATO)
C     
C     WRITE TO PLOTTING FILE
C     
      WRITE (9,2200)
C     
      DO 40 I = 1, JEND
         WRITE (9,2300) STDIST(I), YSDIST(I), DSTOT(I)
   40 CONTINUE
C     
C     IF (ISUM.EQ.1 .OR. IEVT.EQ.1 .OR. IFOFE.EQ.1) THEN
C     AVIRDT=0.0
C     DO 35 L=1,NPLANE
C     AVIRDT=AVIRDT+(SLPLEN(L)*IRDGDX(L))
C     35     CONTINUE
C     AVIRDT=AVIRDT/TOTLEN(NPLANE)
C     
C     IF(IEVT.EQ.1)
C     1      WRITE (30,1100) DAY, MON, YEAR - IBYEAR + 1, PRCP * 1000.0,
C     1      RUNOFF(NPLANE) * EFFLEN(NPLANE) * 1000.0 / TOTLEN(NPLANE),
C     1      AVIRDT, AVEDET, MAXDET, PTDET, AVEDEP, MAXDEP, PTDEP,
C     1      AVSOLE, ENRATO(NPLANE)
C     
C     NOWRES = 1
C     IF(IFOFE.EQ.1)
C     1        WRITE (33,1000) IPLANE, DAY, MON, YEAR - IBYEAR + 1,
C     1        PRCP * 1000.0,
C     1        RUNOFF(IPLANE) * EFFLEN(IPLANE) * 1000.0 / TOTLEN(IPLANE),
C     1        EFFINT(IPLANE) * 3.6E06, PEAKRO(IPLANE) * 3.6E06,
C     1        EFFDRN(IPLANE) / 3600, ENRATO(IPLANE),
C     1        KS(IPLANE) * 3.6E06, WATCON * 1000, LAI(IPLANE),
C     1        CANHGT(IPLANE), CANCOV(IPLANE) * 100, INRCOV(IPLANE) *
C     1        100, RILCOV(IPLANE) * 100, VDMT(IPLANE), RMAGT(IPLANE) +
C     1        RMOGT(NOWRES,IPLANE), KI(IPLANE) * KIADJF(IPLANE) /
C     1        1000000., KR(IPLANE) * KRADJF(IPLANE) * 1000.,
C     1        SHCRIT(IPLANE) * TCADJF(IPLANE), WIDTH(IPLANE),
C     1        OFELOD(IPLANE)
C     
      RETURN
C     
C1000 FORMAT (3(1X,I2),1X,I4,1X,F8.3,1X,F8.3,3(1X,F7.3),F6.3,1X,F7.3,1X,
C     1    F7.3,1X,F7.3,1X,F6.3,3(1X,F7.3),6(1X,F6.3),1X,F8.3)
C1100 FORMAT (2(1X,I2),1X,I5,1X,F5.1,1X,F7.1,1X,F7.3,2(1X,F6.2),1X,F6.1,
C     1    2(1X,F7.2),1X,F6.1,1X,F7.1,1X,F5.2)
 1000 FORMAT (3(F7.2,1X,F9.3,1X,I2,5X))
 1100 FORMAT (///2X,'C.  SOIL LOSS/DEPOSITION ALONG SLOPE PROFILE',//,10
     1    X,'PROFILE DISTANCES ARE FROM TOP TO BOTTOM OF HILLSLOPE'//)
 1200 FORMAT (1X,'DISTANCE',1X,'SOIL',2X,'FLOW',4X,'DISTANCE',3X,'SOIL',
     1    2X,'FLOW',4X,'DISTANCE',3X,'SOIL',2X,'FLOW')
 1300 FORMAT (4X,'(M)',3X,'LOSS',2X,'ELEM',7X,'(M)',5X,'LOSS',2X,'ELEM',
     1    7X,'(M)',5X,'LOSS',2X,'ELEM')
 1400 FORMAT (9X,'(KG/M2)',18X,'(KG/M2)',18X,'(KG/M2)')
 1500 FORMAT (72('-'),/)
 1600 FORMAT (/'NOTE:  (+) SOIL LOSS - DETACHMENT     (-) SOIL LOSS',
     1    ' - DEPOSITION')
 1700 FORMAT (///'III. OFF SITE EFFECTS  OFF SITE EFFECTS',
     1    '  OFF SITE EFFECTS',/,5X,(3(16('-'),2X))/)
 1800 FORMAT (5X,'A.  SEDIMENT LEAVING PROFILE ',F9.3,' KG/M'/)
 1900 FORMAT (9X,F9.3,A,' (BASED ON PROFILE WIDTH OF  ',F9.3,A,')')
 2000 FORMAT (9X,F9.3,A,' (ASSUMING CONTRIBUTIONS FROM ',F9.3,A,')')
 2100 FORMAT (//5X,'B.  SEDIMENT CHARACTERISTICS AND ENRICHMENT')
 2200 FORMAT (1X,'DIST. DOWNSLOPE',1X,'ELEVATION',1X,'SOIL LOSS'/,/,
     1    '   (METERS) ',1X,' (METERS) ',1X,'(KG/M**2)'/)
 2300 FORMAT (1X,F10.3,1X,F10.3,1X,F10.3)
C     
      END
