      SUBROUTINE SEDSTA(JNUM,DLOSS,DSSTD,VMAX,PMAX,VMIN,PMIN,IBEGIN,
     1    IEND,JFLAG,LSEG,DSTOT,STDIST,DELXX)
C
C     + + + PURPOSE + + +
C     FINDS THE MEAN AND STANDARD DEVIATION OF DETACHMENT OR
C     DEPOSITION POINTS WITHIN A SEGMENT.  IT CALLS SR SEDMAX.
C
C     CALLED FROM SEDSEG
C     AUTHOR(S): D.C. FLANAGAN, J.C. ASCOUGH
C
C     VERSION: THIS MODULE MODIFIED FROM WEPP VERSION 2004.7
C     DATE MODIFIED: 9-30-2004
C     MODIFIED BY: D. FLANAGAN
C
C     + + + ARGUMENT DECLARATIONS + + +
C
      INTEGER JNUM, IBEGIN, IEND, JFLAG(100), LSEG
      REAL DLOSS(100), DSSTD(100), PMAX(100), PMIN(100)
      REAL VMAX(100), VMIN(100)
      REAL DSTOT(1000), STDIST(1000), DELXX
C
C
C     + + + ARGUMENT DEFINITIONS + + +
C
C     JNUM   - NUMBER OF THE DETACHMENT OR DEPOSITION REGION
C     DLOSS  - COMPUTED DETACHMENT (OR DEPOSITION) AT A POINT
C     DSSTD  - COMPUTED SAMPLE STANDARD DEVIATION OF SEGMENT
C     VMAX   - MAXIMUM DETACHMENT (OR DEPOSITION) IN A SEGMENT
C     PMAX   - POINT OF MAXIMUM DETACH. OR DEPOS. IN SEGMENT (M)
C     VMIN   - MINIMUM DETACHMENT (OR DEPOSITION) IN A SEGMENT
C     PMIN   - POINT OF MINIMUM DETACH. OR DEPOS. IN SEGMENT (M)
C     DSTOT  - SEDIMENT LOSS DOWN PROFILE AT EACH POINT (KG/M^2)
C     STDIST - DISTANCE DOWN PROFILE AT EACH POINT (M)
C     IBEGIN - BEGINNING OF DEPOSITION/DETACHMENT SEGMENT
C     IEND   - END OF DEPOSITION/DETACHMENT SEGMENT
C     JFLAG  - FLAG FOR WHETHER DEPOSITION OR DETACHMENT OCCURRING
C     LSEG   - FLAG FOR NUMBER OF DEPOSITION/DETACHMENT SEGMENTS
C              ON HILLSLOPE PROFILE
C     DELXX  - DELTA X INCREMENTS BETWEEN EACH POINT DOWN HILSLOPE (M)
C
C     + + + LOCAL VARIABLES + + +
C
      REAL DEVIAT, DSSUM, DSLOSS
      INTEGER I, JJPLAN, NCOMP, NCOMPR
C
C     + + + LOCAL DEFINITIONS + + +
C    DEVIAT :  DEVIATION OF DETACH. (OR DEPOS.) FROM THE MEAN
C    DSSUM  :  SUM OF THE SQUARED DEVIATIONS FROM THE MEAN
C    DSLOSS :  SUM OF THE DETACHMENT (OR DEPOSITION) AT ALL POINTS
C    I      :  COUNTER VARIABLE
C    JJPLAN :  VARIABLE TO ASSIGN OFE NUMBER FOR ARRAY ASSIGNMENT
C    NCOMP  :  USED TO SET JJPLAN
C    NCOMPR :  USED TO FIND WHICH OFE POINT BELONGS TO
C
C     + + + END SPECIFICATIONS + + +
C*******************************************************************
C
      DSSUM = 0.0
      DSLOSS = 0.0
      DSDIST = 0.0
      NCOMPR = 101
      NCOMP = 1
C     
      DO 20 I = IBEGIN, IEND
   10    IF (I.LT.NCOMPR) THEN
            JJPLAN = NCOMP
         ELSE
            NCOMPR = NCOMPR + 100
            NCOMP = NCOMP + 1
            GO TO 10
         END IF
C        
         DSLOSS = DSLOSS + DELXX * DSTOT(I)
         DSDIST = DSDIST + DELXX
   20 CONTINUE
C     
C     
      DLOSS(JNUM) = DSLOSS / DSDIST
C     
C     
      DO 30 I = IBEGIN, IEND
C        
         DEVIAT = DSTOT(I) - DLOSS(JNUM)
         DSSUM = DSSUM + (DEVIAT*DEVIAT)
   30 CONTINUE
C     
      IF (IEND.NE.IBEGIN) THEN
         DSSTD(JNUM) = SQRT((DSSUM/(IEND-IBEGIN)))
      ELSE
         DSSTD(JNUM) = 0.0
      END IF
C     
      CALL SEDMAX(JNUM,VMAX,VMIN,PMAX,PMIN,DSTOT,STDIST,IBEGIN,IEND,
     1    JFLAG,LSEG)
C     
      RETURN
      END
