      REAL FUNCTION SHEAR(A,B,C,X)
C
C     FUNCTION SHEAR CALCULATES NONDIMENSIONAL SHEAR STRESS
C
C     MODULE ADAPTED FROM WEPP VERSION 2004.7 AND CALLED FROM 
C     SUBROUTINE XCRIT (SEE EQUATION 11.4.1 IN NSERL REPORT #10)
C
C     AUTHOR(S): D.C FLANAGAN AND J.C. ASCOUGH II
C     DATE LAST MODIFIED: 9-30-2004
C
C     + + + ARGUMENT DECLARATIONS + + +
C
      REAL A, B, C, X
C
C     + + + ARGUMENT DEFINITIONS + + +
C
C     A - SHEAR STRESS COEFFICIENT FOR CURRENT SLOPE SECTION
C     B - SHEAR STRESS COEFFICIENT FOR CURRENT SLOPE SECTION
C     C - SHEAR STRESS COEFFICIENT FOR CURRENT SLOPE SECTION
C     X - NONDIMENSIONAL DISTANCE AT WHICH SHEAR STRESS IS TO BE 
C         CALCULATED
C
C     + + + LOCAL VARIABLE DECLARATIONS + + +
C
      REAL VALUE
C
C     + + + LOCAL VARIABLE DEFINITIONS + + +
C
C     VALUE - INTERMEDIATE VALUE IN CALCULATING SHEAR STRESS
C
C     BEGIN FUNCTION SHEAR
C
      VALUE = A * X ** 2 + B * X + C
      IF (VALUE.LT.0.0) VALUE = 0.0
      SHEAR = VALUE ** 0.66666667
      IF (SHEAR.LE.0.0) SHEAR = 0.0001
C     
      RETURN
      END
