      FUNCTION SHEARS(Q,SSLOPE,RSPACE,WIDTH,FRCSOL,FRCTRL)
C
C     + + + PURPOSE + + +
C     COMPUTE RILL WIDTH ADJUSTMENTS, CHEZY'S COEFFICIENT FOR RILL
C     FLOW, FLOW DEPTH, WETTED AREA, WETTED PERIMETER, HYDRAULIC
C     RADIUS, AND SHEAR STRESS AT THE END OF THE SLOPE
C
C     CALLED FROM PARAM
C     AUTHOR(S):
C     REFERENCE IN USER GUIDE:
C
C     + + + KEYWORDS + + +
C
C
C     + + + ARGUMENT DECLARATIONS + + +
      REAL Q, SSLOPE, SHEARS
      REAL RSPACE, WIDTH, FRCSOL, FRCTRL
C
C     + + + ARGUMENT DEFINITIONS + + +
C
C     Q      : FLOW DISCHARGE (M**3/S)
C     SSLOPE : CHANNEL SLOPE (M/M)
C
C     + + + LOCAL VARIABLES + + +
      REAL DZ, TOL, U, CHEZCH, SINANG, WP, XSAREA, HYDRAD
C
C     + + + LOCAL DEFINITIONS + + +
C
C      U      : PORTION OF UNIFORM FLOW EQUATION
C      WDTHCK : TEST WIDTH TO CHECK AGAINST TO SEE IF WIDER THAN
C               CURRENT RILL WIDTH
C      CHEZCH : CHEZY C - ROUGHNESS FACTOR
C      DZ     : TRIAL VALVE FOR CHANNEL DEPTH (M)
C      XSAREA : CROSS SECTIONAL AREA OF THE FLOW (M**2)
C      WP     : WETTED PERIMETER OF THE FLOW (M)
C      HYDRAD : HYDRAULIC RADIUS (M)
C      SINANG : SINE OF SLOPE ANGLE
C      TOL    : TOLERANCE VALUE
C
      SAVE
C
C********************************************************************
C
      ACCGAV = 9.807
      WTDENS = 9807.0
C     
C     TOLERANCE VALUE CHANGED BY BAFFAUT, 1996.  DCF 3/97
C     TOL = 5.0E-05
      TOL = 5.0E-06
      Q = ABS(Q)
C     
C     SSLOPE VALUE CHANGED BY BAFFAUT, 1996.  DCF 3/97
C     IF (SSLOPE.LE.0.0) SSLOPE = 0.00001
      IF (SSLOPE.LE.0.0) SSLOPE = 0.000001
C     
C     COMPUTE RILL WIDTH (WIDTH). NOTE THAT WHEN TILLAGE OCCURS
C     RILL WIDTH IS SET TO ZERO IN SR CONTIN (OR SOIL???)
C     
C     USING GILLEY'S RELATIONSHIP
C     COMMENTED OUT - POSSIBLY ADD RWFLAG TO INPUT FILE (1 = TEMP; 2 = PERM)
C     
C     IF (RWFLAG(IPLANE).EQ.1) THEN
C     WDTHCK = 1.13 * Q ** 0.303
C     IF (WIDTH(IPLANE).LT.WDTHCK) WIDTH(IPLANE) = WDTHCK
C     END IF
C     
      IF (WIDTH.GT.RSPACE) WIDTH = RSPACE
C     
C     COMPUTE CHEZY'S COEFFICIENT:
C     
      CHEZCH = SQRT(8.0*ACCGAV/FRCTRL)
C     
C     COMPUTE RILL FLOW DEPTH (DPTHCH(IPLANE)). THIS IS AN ITERATIVE
C     PROCESS TO SOLVE THE UNIFORM FLOW EQUATION:
C     
C     DPTHCH(IPLANE)=((Q/CHEZCH/SQRT(SSLOPE)**
C     (2/3)/WIDTH)*(WIDTH+2*DPTHCH(IPLANE))**(1/3)
C     
      IF (Q.LE.0.) THEN
         DPTHCH = 0.0
      ELSE
         U = (Q/CHEZCH/SQRT(SSLOPE)) ** (2./3.) / WIDTH
         DPTHCH = 0.2 * Q ** .36
   10    DZ = DPTHCH
         DPTHCH = U * (WIDTH+DZ+DZ) ** (1./3.)
         IF (ABS(DZ/DPTHCH-1.).GT.TOL) GO TO 10
      END IF
C     
C     COMPUTE WETTED AREA (XSAREA), WETTED PERIMETER (WP), AND
C     HYDRAULIC RADIUS (HYDRAD):
C     
      XSAREA = DPTHCH * WIDTH
      WP = WIDTH + 2.0 * DPTHCH
      HYDRAD = XSAREA / WP
C     
C     COMPUTE SHEAR STRESS:
C     
C     CORRECTION MADE TO COMPUTE SHEAR STRESS USING THE SINE OF THE
C     SLOPE ANGLE, NOT THE TANGENT OF THE SLOPE ANGLE AS HAS PREVIOUSLY
C     BEEN COMPUTED.  THIS SHOULD ONLY IMPACT RESULTS GREATLY ON STEEPER
C     HILLSLOPES.   DCF   1/21/93
C     SHEARS=WTDENS*SSLOPE*HYDRAD*FRCSOL(IPLANE)/FRCTRL(IPLANE)
C     
      SINANG = SIN(ATAN(SSLOPE))
      SHEARS = WTDENS * SINANG * HYDRAD * FRCSOL / FRCTRL
      RETURN
      END