      SUBROUTINE SLOSS(LOAD,TCEND,WIDTH,RSPACE,EFFDRN,THETA,
     1    SLPLEN,IRDGDX,QSOUT,DSLOST,AVSOLE,QOUT)
C
C     + + + PURPOSE + + +
C     CALCULATES SEDIMENT LOSS (DG/DX) AT POINTS, SEDIMENT YIELD,
C     AND SEDIMENT CONCENTRATION ON A STORM BY STORM BASIS.
C     PASSES RESULTS BACK TO MAIN PROGRAM, TO BE THE OUTPUT IN
C     SUBSEQUENT ROUTINES (SEDOUT, SEDSEG).
C
C     CALLED FROM SUBROUTINE MAIN
C     AUTHOR(S): D. FLANAGAN, J. ASCOUGH
C
C     VERSION: THIS MODULE MODIFIED FROM WEPP V2004.7 CODE
C     DATE LAST MODIFIED:  4-1-2005
C
C     + + + ARGUMENT DECLARATIONS + + +
C
      REAL LOAD(101), TCEND, WIDTH, RSPACE, EFFDRN
      REAL THETA, SLPLEN
      REAL IRDGDX, QSOUT, DSLOST(100)
      REAL AVSOLE, QOUT
C     
C
C     LOAD   - NONDIMENSIONAL SEDIMENT LOAD AT POINTS DOWN SLOPE
C     TCEND  - SEDIMENT TRANSPORT CAPACITY AT END OF THE AVERAGE
C              UNIFORM SLOPE PROFILE THAT PASSES THROUGH THE
C     WIDTH  - RILL WIDTH (M)
C     RSPACE - RILL SPACING (M)
C     EFFDRN - EFFECTIVE DURATION OF RUNOFF (S)
C     THETA  - NONDIMENSIONAL INTERRILL DETACHMENT PARAMETER
C              ENDPOINTS OF AN OFE  (KG/S*M).
C     SLPLEN - SLOPE LENGTH OF OFE (M)
C     PEAKRO - PEAK RUNOFF RATE (M/S)
C     RUNOFF - RUNOFF DEPTH (M)
C     EFFLEN - EFFECTIVE LENGTH OF RUNOFF DOWN PROFILE (M)
C     FRCFLW - FRACTION OF EACH PARTICLE TYPE IN FLOW
C     IRDGDX - INTERRILL CONTRIBUTION TO DG/DX) IN (KG/M^2)
C     QSOUT  - SEDIMENT DISCHARGE AT END OF CURRENT OFE (KG/S*M)
C     DSLOST - NET SOIL LOSS/GAIN AT EACH POINT ON HILLSLOPE FOR
C              A STORM EVENT (TIME*DG/DX) - (KG/M**2)
C     AVSOLE - STORM SEDIMENT LOSS (KG/M)
C     ENRATO - ENRICHMENT RATIO OF SPECIFIC SURFACE AREA OF SEDIMENT
C     QOUT   - FLOW DISCHARGE OUT OFE (M^3/S*M)
C
C
C     + + + LOCAL VARIABLES + + +
C
      INTEGER J
      REAL DSLOD1, DSLOD2
C
C     REAL CSEDLS(MXPLAN)
C
C     DSLEND - DIMENSIONAL SEDIMENT LOAD AT OFE END - (KG/M) 
C     DSLOD1 - DIMENSIONAL SEDIMENT LOAD AT POINT - (KG/M) 
C     DSLOD2 - DIMENSIONAL SEDIMENT LOAD AT POINT - (KG/M)
C     CSEDLS - SEDIMENT LOSS FROM CONTOURED OFES IN (KG)
C
C     + + + END SPECIFICATIONS + + +
C
      SAVE
C
C     DATA CSEDLS /75 * 0.0/
C
C
C     INITIALLY, DO OUTPUT ONLY FOR A SINGLE STORM - DCF 9-29-2004
C     IMODEL = 2
C
C     INITIALIZE LOAD VARIABLES
C
C     DSLEND = 0.0
      DSLOD1 = 0.0
      DSLOD2 = 0.0
      DO 10 J = 2, 101
         DSLOST(J-1) = 0.0
   10 CONTINUE
C     
C     ASSUME FOR NOW THAT THE STANDALONE WILL NOT CALL HYDOUT,
C     SINCE IT PRODUCES AND WRITES HYDROLOGY OUTPUT OTHER THAN
C     THE MAIN DETAILED SINGLE STORM INFORMATION.  INSTEAD, WILL
C     NEED TO CALL PRINT.FOR FROM THE MAIN PROGRAM.
C     
C     IF (IOUTPT.EQ.1.AND.IMODEL.EQ.1) CALL HYDOUT(JUN,IDOUT,WMELT)
C     
C     CALCULATE DIMENSIONAL SEDIMENT LOAD AT BEGINNING OF OFE (X=0)
C     
      DSLOD1 = LOAD(1) * EFFDRN * TCEND * WIDTH / RSPACE
C     
C     DCF  ASSUME FOR NOW THAT THE STANDALONE DOES NOT DEAL WITH CONTOURING
C     DCF  SO, COMMENT OUT CODE RELATED TO CONTOUR SITUATION EROSION.
C     DCF  IF CONTOURS PRESENT, THEN COMPUTE AN AVERAGE DETACHMENT RATE ON
C     DCF  THE OFE USING THE SEDIMENT DISCHARGE AT THE END OF THE CONTOURS.
C     DCF  CONTOURS ARE ASSUMED NOT TO FAIL IF PRESENT.
C     DCF
C     DCF START OF CONTOUR ELSE-IF
C     DCF
C     DCF  OFELOD(IPLANE)=0.0
C     DCF  IF (CONSEQ(NOWCRP,IPLANE).NE.0) THEN
C     DCF    DSLEND = LOAD(101) * EFFDRN(IPLANE) * TCEND * WIDTH(IPLANE) /
C     DCF 1           RSPACE(IPLANE)
C     DCF  AVSOLS = DSLEND / CNTLEN(IPLANE)
C     DCF
C     DCF  DO 20 J = 2, 101
C     DCF    DSLOST(IPLANE,J-1) = AVSOLS
C     DCF20   CONTINUE
C     DCF
C     DCF
C     DCF  FOLLOWING LINE ADDED 2/4/91 TO CALCULATE INTERRILL CONTRIBUTION
C     DCF  FOR AN OFE ON WHICH CONTOURS HAVE HELD
C     DCF
C     DCF  IRDGDX(IPLANE) = (THETA*TCEND*EFFDRN(IPLANE)*WIDTH(IPLANE)) / (
C     DCF 1                 RSPACE(IPLANE)*CNTLEN(IPLANE))
C     DCF
C     DCF  6-19-2002 NEED TO REPORT THE SEDIMENT LEAVING THE SIDES
C     DCF  OF EACH CONTOURED OFE IN THE OUTPUT FILE, AS WELL AS THE
C     DCF  ACCUMULATED SEDIMENT LEAVING THE SIDES OF THE OFES. ADD
C     DCF  NEW VARIABLE "AVSOLC(IPLANE)" TO TRACK THE STORM SEDIMENT
C     DCF  LOSS FROM THE CONTOURED OFE SIDES.   DCF
C     DCF
C     DCF  AVSOLC(IPLANE) = DSLEND
C     DCF
C     DCF   COMPUTE THE TOTAL SEDIMENT LEAVING THE CONTOURED OFE TO THE
C     DCF   SIDE, BY FINDING AN EQUIVALENT WIDTH (OFE AREA/CONTOUR LGTH)
C     DCF  CSEDLS(IPLANE) = AVSOLC(IPLANE)*
C     DCF 1                 (SLPLEN(IPLANE)*FWIDTH(1)/CNTLEN(IPLANE))
C     DCF
C     DCF   SET THE AVERAGE SEDIMENT DISCHARGE OFF THE PLANE EQUAL TO ZERO
C     DCF   SINCE IF CONTOURS HOLD NO SEDIMENT REACHES THE NEXT OFE FROM
C     DCF   ABOVE.
C     DCF
C     DCF  AVSOLS = 0.0
C     DCF
C     DCF ELSE IF NO CONTOURS ARE PRESENT ON THE OFE
C     
C     CALCULATE THE NET SEDIMENT LOSS OR GAIN AT A POINT BY TAKING
C     THE DIFFERENCE BETWEEN THE SEDIMENT LOAD AT THE POINTS DIVIDED
C     BY THE DISTANCE BETWEEN THE POINTS.
C     
C     DCF   ELSE
C     
      DO 20 J = 2, 101
         DSLOD2 = LOAD(J) * EFFDRN * TCEND * WIDTH / RSPACE
         DSLOST(J-1) = (DSLOD2-DSLOD1) / (SLPLEN*0.01)
         DSLOD1 = DSLOD2
   20 CONTINUE
C     OFELOD(IPLANE)=DSLOD1
C     
C     COMPUTE INTERRILL CONTRIBUTION TO SEDIMENT LOSS.
C     
      IRDGDX = (THETA*TCEND*EFFDRN*WIDTH) / (RSPACE*SLPLEN)
C     
C     
C     AVSOLS = DSLOD2 / CNTLEN(IPLANE)
C     AVSOLS = DSLOD2 / SLPLEN(IPLANE)        
C     
C     DCF  END OF CONTOUR ELSE-IF
C     
C     DCF  END IF
C     DCF
C     DCF SUMMING FOR MONTHLY AND ANNUAL DSLOST
C     DCF
C     DCF  DO 40 J = 2, 101
C     DCF    DSMON(IPLANE,J-1) = DSMON(IPLANE,J-1) + DSLOST(IPLANE,J-1)
C     DCF    DSYEAR(IPLANE,J-1) = DSYEAR(IPLANE,J-1) + DSLOST(IPLANE,J-1)
C     DCF    DSAVG(IPLANE,J-1) = DSAVG(IPLANE,J-1) + DSLOST(IPLANE,J-1)
C     DCF   40 CONTINUE
C     
C     START OF IPLANE=NPLANE ELSE-IF  (THIS THE LAST
C     OFE ON THE CURRENT HILLSLOPE)
C     
C      IF (IPLANE.EQ.NPLANE) THEN
C        
C        IF CONTOURS ARE NOT PRESENT THE SEDIMENT REACHING THE END OF
C        THE HILLSLOPE IS EQUAL TO THE SEDIMENT LOAD AT THE LAST POINT
C        OF THE LAST OFE ON THE CURRENT HILLSLOPE.
C        ELSE - IF CONTOURS ARE PRESENT THEN THEY ARE ASSUMED TO NOT
C        FAIL AND ALL SEDIMENT IS ASSUMED ROUTED TO THE SIDE OF THE
C        HILLSLOPE AND NONE REACHES THE END OF THE OFE.  
C        6/26/2002 - A NEW CALCULATION FOR "AVSOLE" IS MADE FOR THE
C        CASE OF A CONTOURED HILLSLOPE - THAT INCLUDES ALL SEDIMENT
C        LEAVING THE PROFILE IN ANY DIRECTION.
C        
C        DCF   SUMSLC = 0.0
C        DCF   DO 45 J = 1,NPLANE
C        DCF     SUMSLC = SUMSLC + CSEDLS(J)
C        45    CONTINUE
C        
C        DCF    IF (QOUT.GT.0.0 .AND. CONSEQ(NOWCRP,NPLANE).EQ.0)THEN
C        DCF      AVSOLE = (SUMSLC + DSLOD2*FWIDTH(1))/FWIDTH(1)
C        DCF    ELSE
C        DCF      AVSOLE = SUMSLC/FWIDTH(1)
C        DCF    ENDIF
C        
         IF (QOUT.GT.0.0) THEN
            AVSOLE = DSLOD2
         ELSE
            AVSOLE = 0.0
         END IF
C        
         IF (AVSOLE.LT.0.0) AVSOLE = 0.0
C     
C     DCF    AVSOLM = AVSOLM + AVSOLE
C     DCF    AVSOLY = AVSOLY + AVSOLE
C     DCF    AVSOLF = AVSOLF + AVSOLE
C     
C     DCF    IRSOLD = AVSOLE * IRFRAC
C     DCF    IRSOLM = IRSOLM + IRSOLD
C     DCF    IRSOLY = IRSOLY + IRSOLD
C     DCF    IRSOLT = IRSOLT + IRSOLD
C     
CC    DCF   SUMMING FOR WEIGHTED ENRICHMENT RATIO
CC    DCF   SETS SINGLE STORM AND SUMS FOR MONTHLY AND ANNUAL
C     
C     DCF    ENRMM1 = ENRMM1 + (ENRATO(NPLANE)*AVSOLE)
C     DCF    ENRMM2 = ENRMM2 + AVSOLE
C     DCF    ENRYY1 = ENRYY1 + (ENRATO(NPLANE)*AVSOLE)
C     DCF    ENRYY2 = ENRYY2 + AVSOLE
C     DCF    ENRFF1 = ENRFF1 + (ENRATO(NPLANE)*AVSOLE)
C     DCF    ENRFF2 = ENRFF2 + AVSOLE
C     
C     DCF    DO 50 I = 1, NPART
C     
C     DCF      FRCMM1(I) = FRCMM1(I) + (FRCFLW(I,NPLANE)*AVSOLE)
C     DCF      FRCMM2(I) = FRCMM2(I) + AVSOLE
C     DCF      FRCYY1(I) = FRCYY1(I) + (FRCFLW(I,NPLANE)*AVSOLE)
C     DCF      FRCYY2(I) = FRCYY2(I) + AVSOLE
C     DCF      FRCFF1(I) = FRCFF1(I) + (FRCFLW(I,NPLANE)*AVSOLE)
C     DCF      FRCFF2(I) = FRCFF2(I) + AVSOLE
C     
C     DCF   50   CONTINUE
C     
C     DCF SEDIMENT CONCENTRATIONS ARE NOT USED ANYWHERE IN
C     DCF THE HILLSLOPE OUTPUT (THEY ARE PASSED TO THE 
C     DCF WATERSHED COMPONENTS TO BE USED THERE).  FOR NOW,
C     DCF COMMENT OUT FOLLOWING SECTION AND DO NOT COMPUTE
C     DCF SEDCON.  DCF  9-29-2004
C     
C     DCF   COMPUTE SEDIMENT CONCENTRATION (KG/M**3),
C     DCF   FOR EACH PARTICLE SIZE LEAVING THE HILLSLOPE,
C     DCF   AVSOLE IS IN (KG/M) AND RUNVOL IS IN (M**3)
C     DCF
C     DCF    IF (IPLANE.EQ.NPLANE) THEN
C     DCF      DO 60 IPART = 1, NPART
C     DCF        IF (PEAKRO(NPLANE).LE.0.0) THEN
C     DCF          SEDCON(IPART,NPLANE) = 0.0
C     DCF        ELSE
C     DCF          SEDCON(IPART,NPLANE) = AVSOLE / (RUNOFF(NPLANE)*
C     DCF 1            EFFLEN(NPLANE)) * FRCFLW(IPART,NPLANE)
C     DCF        END IF
C     DCF   60     CONTINUE
C     END IF
C     
C     
C     END OF IPLANE=NPLANE IF-ELSE
C     
C     END IF
C     
C     
C     IF CONTOURS HOLD, QSOUT EQUALS ZERO SINCE NO SEDIMENT REACHES
C     THE NEXT OFE.  IF CONTOURS FAIL, QSOUT EQUALS THE SEDIMENT LOAD
C     AT THE END OF THE CURRENT OFE.
C     IF CONTOURS EXIST THEY ARE ASSUMED NOT TO FAIL
C     
C     DCF  IF (CONSEQ(NOWCRP,IPLANE).EQ.0) THEN
C     DCF    IF (QOUT.GT.0.0) THEN
C     DCF      QSOUT = DSLOD2 / EFFDRN(IPLANE)
C     DCF    ELSE
C     DCF      QSOUT = 0.0
C     DCF    END IF
C     DCF  ELSE
C     DCF    QSOUT = 0.0
C     DCF  END IF
C     
      IF (QOUT.GT.0.0) QSOUT = DSLOD2 / EFFDRN
C     
C     
      RETURN
      END
