      SUBROUTINE UNDFLO(FACTOR,EXPON)
C
C     SUBROUTINE UNDFLO PROTECTS AGAINST NUMERIC UNDERFLOWS 
C     AND OVERFLOWS
C
C     MODULE ADAPTED FROM WEPP VERSION 2004.7 AND CALLED FROM 
C     SUBROUTINE ENRICH AND FUNCTIONS DEPEQS/DEPEND, 
C
C     AUTHOR(S): D.C. FLANAGAN AND J.C. ASCOUGH II
C     DATE LAST MODIFIED:  9-30-2004
C
C     + + + ARGUMENT DECLARATIONS + + +
C
      REAL FACTOR, EXPON
C
C     + + + ARGUMENT DEFINITIONS + + +
C
C     FACTOR -
C     EXPON  -
C
C     + + + LOCAL VARIABLES + + +
C
      REAL EXP10, POWER
C
C     + + + LOCAL VARIABLE DEFINITIONS + + +
C
C     EXP10 -
C     POWER -
C
C     + + + DATA INITIALIZATIONS + + +
C
      DATA POWER /30.0/
C
C     BEGIN SUBROUTINE UNDFLO
C
      IF (FACTOR.GT.0.0) THEN
         EXP10 = EXPON * ALOG10(FACTOR)
C        
         IF (ABS(EXP10).GT.POWER) THEN
            FACTOR = 0.0
            EXPON = 1.0
         END IF
C     
      END IF
C     
      RETURN
      END
